
try{document.execCommand('BackgroundImageCache',false,true);}catch(e){}
var cpI=new Array(10,11,12,14,15);var cpL=new Array;var rst={rs:{tl:{radius:5},tr:{radius:5},bl:{radius:5},br:{radius:5},antiAlias:true},init:function(v){this.rs.tl.radius=v;this.rs.tr.radius=v;this.rs.bl.radius=v;this.rs.br.radius=v;}};var FFC=true;var IE6=false;var IE7=false;var IE8=false;var KDE=false;var OPR=false;var mcval='FFFFFF';var lcval='000000';var lmsg1="Loading your image";var lmsg2="Crop Image";var lmsg3="Cancel Crop";var otxt_o="Optimized Image";var otxt_p="Preview";var bmsg1="Border Preview";var bmsg2="click 'apply changes' to save or";var bmsg3="exit preview";var cmsg4="ratio";var tmsg1="Border";var tmsg2="no borders";var tmsg4="Corners";var rmsg="Rounded";var cpmsg="click for more colours";var ina=false;var azz=false;var ax98=null;var az99=null;try{if(isv(ini)){ina=ini;}}catch(e){ina=false;}
try{if(isv(az)){azz=az;}}catch(e){azz=false;}
try{if(isv(hr96)){ax98=hr96;}}catch(e){ax98=null;}
try{if(isv(ax97)){ax99=ax97;}}catch(e){ax99='0,0';}
var pG={vh:0,vw:0,h:220,w:200,tp:0,lp:0,t:0,l:0,ro:10,t_ie:0,tp_ie:0,be_ie:false,re_ie:false,br_ie:false,pr_ie:false,a:'bc10',p:'bc10',r:false,tID:null,br:false};var dyn={i:null,i79:null,bi:null,bfid:{},bdd:{},bdo:{},bdc:{},bdt:{},bn:null,rn:null,rbc:'',rt:false,rtn:null,bt:null,dim1:null,dim2:null,dwn:null};var lt={b:{a:false,i:null},c:{a:false,i:null},n:{a:false,i:null},p:{a:false,i:null},t:{a:false,i:null},u:{a:false,i:null}};var stat={bp:null,ci:null,cw:null,en:null};function icr(x){if(!lt.n.a||!lt.b.a)return false;return document.iform.round[x].checked;};function icr_set(x){if(!lt.n.a||!lt.b.a)return;else document.iform.round[x].checked=true;};function iDynam(){var b=$('i078b');if(!isv(b))b=$('i078');dyn.bi=b.cloneNode(true);dyn.bi.id='i078';dyn.i=$('i078').cloneNode(true);if(lt.n.a){dyn.rt=icr(1);dyn.rn=stat.en.cloneNode(true);var ht=dyn.bi.height;if(IE6)ht=ht+1;dyn.rn.setStyle({height:ht+'px',width:dyn.bi.width+'px'});dyn.rn.id='i078';dyn.rn.style.backgroundImage='url('+dyn.bi.src+')';if(pG.br){var r=pG.ro+'px';dyn.rn.style.MozBorderRadius=r;dyn.rn.style.borderRadius=r;dyn.rn.style.WebkitBorderRadius=r;dyn.rn.style.KhtmlBorderRadius=r;}
dyn.rbc=getBG($('i078e'));};};function iStat(){function bp(){var b1="<h4 id='u9'>";var b2="</h4><p id='um8'>";var b3="&nbsp;<a href='javascript:void(0);' onclick='clickP();'><span class='u1'>";var b4="</span></a></p>";stat.bp=b1+bmsg1+b2+bmsg2+b3+bmsg3+b4;};function ci(){stat.ci=stat.en.cloneNode(true);stat.ci.id='cd97';var c1="<label for='cd98' id='cd98b'>&nbsp;<span class='off'>&#8596;</span></label><input id='cd98' name='cd98' value='0' size='5' maxlength='4'/><label for='cd99' id='cd99b'>&nbsp;<span class='off'>&#8593;</span></label><input id='cd99' name='cd99' value='0' size='5' maxlength='4'/><input type='checkbox' id='cd94' name='cd94'/><label for='cd94' id='cr88'>&nbsp;<span class='off'>";var c2="</span></label>";stat.ci.innerHTML=c1+cmsg4+c2;};function cw(){stat.cw=stat.en.cloneNode(true);stat.cw.id='Htc0';var c10="<table id='tc0' class='tc0c' width='100%' cellspacing='0' cellpadding='0' summary='color palette'><tr>";var c20="<td class='tcxd' colspan='2'><a href='javascript:void(0);' id='cpk' onclick='cpSh(this.id)' onmouseover='cpV0()' onmouseout='cpV1()' alt='"+cpmsg+"' + title='"+cpmsg+"'><img height='18' id='cpki' width='18' src='lib/styles/colorp.gif' alt=''/></a></td>";var c25="<td class='tcxc' colspan='6'";var c30="><a href='javascript:void(0);' onclick='cpal0();'><img height='11' width='10' src='lib/styles/x.gif' alt='x' title=''/></a></td>";var c40="</tr>";var pcol=new Array('#FFFFFF','#eeeeee','#dddddd','#cccccc','#999999','#666666','#333333','#000000','#DAECF6','#B1DCF7','#8AA6D6','#1D71B8','#33348E','#CCCCFF','#8792C7','#5F5CA5','#DFF0D8','#CBDE9D','#678433','#345E29','#003300','#E9E9BA','#F7F7D9','#FFFF66','#F8E3F8','#FFCCFF','#B03636','#861114','#670000','#81623D','#BA9B6F','#E0922E');var bc,j;for(var i=0;i<pcol.length;i++){j=i+1;bc=(pcol[i]=="#FFFFFF")?"#eeeeee":pcol[i];if(j%8==1)c40+="<tr>";c40+="<td><div id='tc"+i+"' style='background-color:"+pcol[i]+";border:1px solid "+bc+";'></div></td>";if(j%8==0)c40+="</tr>";};c40+="</table>";if(IE6){c25="<td class='tcxc' colspan='8'";c20="";};stat.cw.innerHTML=c10+c20+c25+c30+c40;};function getbdo(){var a,b,j,i,ok=false,n=cpI.length;for(i=0;i<n;i++){j=cpI[i];b=$(dyn.bfid[j]);if(isv(b)){a=0;var vel=$(bpID(j));if(isv(vel)){a=vel.value;}
dyn.bdo.c[j]=b.value;dyn.bdc.c[j]=b.value;dyn.bdo.v[j]=a;dyn.bdc.v[j]=a;}}};stat.en=$('Hz9').cloneNode(true);if(lt.b.a){dyn.bt=stat.en.cloneNode(true);dyn.bt.id='Hbb0';$('cd5').style.background='1px 5px url(lib/styles/borderP.gif) no-repeat';};if(lt.c.a){dyn.cr=$("cr0").cloneNode(true);};dyn.bp=$('cd5').cloneNode(true);if(lt.p.a){getbdo();setCVal(dyn.bdo);};if(lt.n.a){dyn.rtn=$('rb1').cloneNode(true);dyn.rtn.id='bb2';};if(lt.b.a)bp();if(lt.c.a)ci();if(lt.p.a&&IE6)cw();};function initG(){function swProp(x10,x11,x12,x14,x15){return{10:x10,11:x11,12:x12,14:x14,15:x15};}
function inTx(){if(lt.b.a){tmsg1=$('bl10').innerHTML;tmsg4=$('cc1').innerHTML;}};function sO(){var r=document.body.style;return r.WebkitBorderRadius!==undefined||r.MozBorderRadius!==undefined||r.borderRadius!==undefined;};dyn.bdd.v=swProp(1,12,1,0,10);dyn.bdd.c=swProp('#cccccc','#ffffff','#eeeeee','#ffffff','#ffffff');dyn.bdo.v=swProp();dyn.bdo.c=swProp();dyn.bdc.v=swProp();dyn.bdc.c=swProp();dyn.bdt.c=swProp();dyn.bfid=swProp('bColor','pColor','eColor','tColor','gColor');pG.br=sO();function vdim(){pG.vw=window.innerWidth;if(!isv(pG.vw))pG.vw=document.documentElement.clientWidth;pG.vh=window.innerHeight;if(!isv(pG.vh))pG.vh=document.documentElement.clientHeight;};function calcLab(){var n=cpI.length;var d='Pick a Color';for(var i=0;i<n;i++){var k=cpI[i];var j=$('bl'+k);if(isv(j)){var s=j.innerHTML;var sl=s.lastIndexOf(":");if(sl>0)s=s.substr(0,sl);cpL[k]=s;}
else cpL[k]=d;};};function calcP(){var ol=0;var ot=0;ot=$('efx').offsetTop+20;if(lt.b.a){ot=$('bc10z').offsetTop;ol=$('bc11z').offsetLeft;}else if(lt.t.a){ol=$('bc14z').offsetLeft;}else{ol=$('i6').offsetLeft;}
ol=$('i078').offsetLeft+$('iopt').offsetLeft;pG.tp=$('iopt').offsetTop+$('images').offsetTop;pG.lp=ol;pG.t=$('iopt').offsetTop+$('ef').offsetTop+ot-pG.h+20;pG.l=ol-(pG.w/2)+20;};function loadSV(){var z='';for(var i=hSV;i>=0;i--)z+="<div style=\"BACKGROUND: #"+hsv2hex([Math.round((360/hSV)*i),100,100])+";\"><\/div>";$('Hmodel').innerHTML=z;};var cp="<div id='cpHead'><span id='cpTit'>&nbsp;</span></div><div id='SV'><div id='SVslide'><br/></div></div><form id='H' action=''><div id='Hslide'><br/></div><div id='Hmodel'></div></form><div id='cpSwatch'></div><input type='text' id='cpHEX' name='cpHEX' value='eeeeee' size='7' maxlength='6'/>";var cp1="<div id='cpBut'>";var cp2="<a href='javascript:void(0);' id='closeHEX' onclick='pClose();'><img src='lib/styles/pno.gif' height='15' width='15' title='Cancel'/></a><a href='javascript:void(0);' id='setHEX' onclick='pSet();'><img src='lib/styles/pok.gif' height='20' width='20' title='OK'/></a></div>";cp=cp+cp1+cp2;if(lt.p.a){var p=$('cp');var np=p.cloneNode(true);np.innerHTML=cp;var x=p.parentNode.replaceChild(np,p);if(!pG.br){if(!OPR)curvyCorners(rst.rs,"#cp");}
loadSV();vdim();calcLab();calcP();}
if(lt.n.a)pG.r=icr(1);inTx();};function initAT(){if(isv($('bc10'))){lt.b.i='bc10';lt.b.a=true;};if(isv($('bc14'))){lt.t.i='bc14';lt.t.a=true;};if(isv($('bc15'))){lt.n.i='bc15';lt.n.a=true;};if(lt.n.a||lt.t.a||lt.b.a){lt.p.i='Htc0';lt.p.a=true;};if(isv($('cb4'))){lt.c.i='cb4';lt.c.a=true;};if(isv($('uf'))){lt.u.i='uf';lt.u.a=true;};};function isv(x){if((x==undefined)||(x==null))return false;return true;};function geti(i){return i.substr(2,2);};function bID(n,s){if(isv(s))return'bc'+n+s;return'bc'+n;};function bpID(n){return'bp'+n;};if(ax98){if(azz){if(window.XDomainRequest){parent.postMessage("#"+ax99,ax98);}else{parent.location=ax98+"#"+ax99;}}};function icw(){$('i11').src="lib/styles/wait.gif";};function icd(){$('i11').src="lib/styles/waitspc.gif";};function showO(){var o=$('Otxt');o.innerHTML=otxt_o;};function showP(){var o=$('Otxt');o.innerHTML=otxt_p;icd();};function Von(x,f){if(isv(x)){if(f)x.style.visibility="visible";else x.style.visibility="hidden";};};function xIn(x,y,z){if(isv(z))x.innerHTML=z;else if(!isv(y))x.innerHTML="";else x.innerHTML=y.innerHTML;};function getBG(x){if(x){if(IE7||IE6)return x.currentStyle['backgroundColor'];else return x.getStyle('background-color');}else{return"#eeeeee";}};function setBG(x,c){if(x){x.style.backgroundColor=c;}};function inp(){var b=$('bb2');if(isv(b))return b.parentNode.id=="bbt00";return false;};function vpal1(i,l){if(!isv(i)){if(l)i.style.color="red";return-1;}
var y=i.value;if(isNaN(parseInt(y,10))){if((y.match(/[(\s)/]/g))||(y=='')){if(l)i.style.color="black";return 0;}
else{if(l)i.style.color="red";return-1;}}else{if(y.match(/[^0123456789]/g)){if(l)i.style.color="red";return-1;}
else{if(l)i.style.color="black";return y;}}};function rgb2hex(r){return(toHex(r[0])+toHex(r[1])+toHex(r[2]));};function toHex(v){v=Math.round(Math.min(Math.max(0,v),255));return("0123456789ABCDEF".charAt((v-v%16)/16)+"0123456789ABCDEF".charAt(v%16));};function stripRGB(c){if(isv(c)){if(c.substr(0,1)=='#'){return c;}else if(c.substr(0,3)=='rgb'){var nc=c.substr(4);nc=nc.replace(')',"");nc=nc.replace(/' '/g,"");var r=nc.split(',');c="#"+rgb2hex(r);return c;}};return c;};function bub(e){if(!e)var e=window.event;if(isv(e)){e.cancelBubble=true;if(e.stopPropagation)e.stopPropagation();}};function detKDE(){var a=navigator.vendor;if(isv(a)){if(a.indexOf('KDE')!=-1)return true;}
return false;}
function styleI(a){var i=0,n=a.length;for(i=0;i<n;i++){var t=a[i].type;if(t!='hidden'){if((t=='text')||(t=='radio')||(t=='checkbox')||(t=='submit')||(t=='file')){a[i].style.backgroundColor='#'+mcval;;}}}}
function styleForms(){var a=Form.getElements($('iform'));styleI(a);a=Form.getElements($('uf'));styleI(a);}
function detB(){if(window.opera){FFC=true;OPR=true;}
else if(document.all){FFC=false;}else{FFC=true;}
if(IE6)FFC=false;if(IE7)FFC=false;}
function cdh(){var t=$('cd97');if(isv(t)){var b=dyn.bp.cloneNode(true);t.parentNode.replaceChild(b,t);if(lt.b.a){eBPre1();}}};function cds(){var t=$('cd5');if(isv(t)){var c=stat.ci.cloneNode(true);t.parentNode.replaceChild(c,t);cset();}};function sfz(){icw();$('undoCrop').value=1;document.iform.submit();return false;};function scr(){function cpreV(){icw();var g=$('i078');if(!dyn.rt)g.parentNode.replaceChild(dyn.bi,g);setCVal(dyn.bdo);getCVal();if(!dyn.rt){bDis();setDimC();}
g=$('i078');rcr();var h=Math.round(g.height/2);var w=Math.round(g.width/2);var x1=Math.round(g.width/4);var y1=Math.round(g.height/4);cds();var x2=w+x1;var y2=h+y1;$('cd99').value=h;$('cd98').value=w;$('newSize').value=w;mc=new Cropper.Img('i078',{onEndCrop:onEndCrop,displayOnInit:true,onloadCoords:{x1:x1,y1:y1,x2:x2,y2:y2}});$('cb4').innerHTML="<span class='u1'>"+lmsg3+"</span>";icd();};if(cv){scr2();}
else{cv=true;cpreV();}};function scr2(){function cpre0(e){showO();zb();resetDimC();var i=$('i078');i.parentNode.replaceChild(dyn.i,i);if($('in1').checked==true)$('newSize').value=dyn.i.width;else $('newSize').value=dyn.i.height;icd();};cv=false;if(mc)mc.remove();cpre0();cdh();rcr();$('cb4').innerHTML="<span class='u1'>"+lmsg2+"</span>";};function rcr(){$('x1').value=0;$('y1').value=0;$('x2').value=0;$('y2').value=0;if(mc)mc.remove();};var xxa=new ept();var mc=null;var cv=false;function onEndCrop(coords,dimensions){$('x1').value=coords.x1;$('y1').value=coords.y1;$('x2').value=coords.x2;$('y2').value=coords.y2;if($('in1').checked==true)$('newSize').value=$('cd98').value;else $('newSize').value=$('cd99').value;};function bDown(){var o=false;var r=null;var x=$('bb2');var b=x.cloneNode(true);var y=$('rr1');if(isv(y))o=true;if(o){r=y.cloneNode(true);};var bt=$('Hbb0');bt.parentNode.replaceChild(dyn.cr,bt);var t=$('bb1');var tt=t.appendChild(b);if(o){t=$('rr0');tt=t.appendChild(r);Event.stopObserving($('bp15'),'keyup',brall);};if(dyn.rt)icr_set(1);else icr_set(0);xIn($('rprev1'));if(isv(dyn.dwn)){var dl=$('rprev0');dl.appendChild(dyn.dwn);}
$('dm1').innerHTML=dyn.dim1;var d=$('dm2');if(isv(d)){d.innerHTML=dyn.dim2;};Von($('bb0'),true);Von($('bbpr'),true);Von($('b7'),true);if(o)Von($('rr7'),true);};function bUP(){var o=false;var r=null;var t1="<table summary='border preview tools' cellspacing='0' cellpadding='0'><tr><td class='bt1' style='padding-right:5px;'>";var t2="</td><td id='bbt00'><div id='bb2'>";var t3="</div></td><td><a href='javascript:void(0);' id='ccb8'><span class='u1'>";var t4="</span></a></td></tr>";var t5="<tr><td class='bt1'>";var t6="</td><td colspan='2'><div id='rr1'>";var t7="</div></td></tr>";var t8="</table><div class='cline'></div>";var c=$('cr0');var x=$('bb2');var rv=null;if(lt.n.a)rv=$('bp15').value;var b=x.cloneNode(true);x.parentNode.removeChild(x);var y=$('rr1');if(isv(y))o=true;if(o){r=y.cloneNode(true);y.parentNode.removeChild(y);};Von($('bb0'),false);Von($('bbpr'),false);Von($('b7'),false);if(o)Von($('rr7'),false);var t=t1+tmsg1+t2+b.innerHTML+t3+tmsg2+t4;if(o)t+=t5+tmsg4+t6+r.innerHTML+t7;t+=t8;dyn.bt.innerHTML=t;c.parentNode.replaceChild(dyn.bt,c);if(pG.r){icr_set(1);Von($('ccb8'),false);}
else icr_set(0);if(pG.r&&lt.n.a)$('bp15').value=rv;var d1=$('dm1');dyn.dim1=d1.innerHTML;xIn(d1);var d2=$('dm2');if(isv(d2)){dyn.dim2=d2.innerHTML;xIn(d2);};xIn($('rprev1'),null,stat.bp);var dl=$('dl');if(isv(dl)){dyn.dwn=dl.cloneNode(true);$('rprev0').removeChild(dl);}else{dyn.dwn=null;}};function bHall(f){if(ina){var o=$('i079');if(isv(o)){Von($('Xtxt'),f);Von(o,f);};};};function setDimC(){var h=$('i078').height+"px";var ih=$('i078e').getStyle('height');if(ih!=h)$('i078e').setStyle({height:h});var w=$('i078').width;if(FFC){var bb=dyn.bdc.v[11];var pp=dyn.bdc.v[12];var gg=parseInt(w)+parseInt(bb)+parseInt(pp)+parseInt(pp)+parseInt(bb);gg=gg+"px";$('i078c').setStyle({width:gg});}
if(!FFC){if(IE7){var ow=$('i078e').getStyle('width');var bb=dyn.bdc.v[11];var pp=dyn.bdc.v[12];var gg=parseInt(w)+parseInt(bb)+parseInt(pp)+parseInt(pp)+parseInt(bb);gg=gg+"px";if(ow!=w)$('i078c').setStyle({width:gg});}else{var ow=$('i078e').getStyle('width');w=w+"px";if(ow!=w)$('i078c').setStyle({width:w});}}};function resetDimC(){if((FFC)||(IE7)){var h=dyn.i.height+"px";var w=dyn.i.width+"px";var ih=$('i078e').getStyle('height');if(ih!=h)$('i078e').setStyle({height:h});var ow=$('i078e').getStyle('width');if(ow!=w)$('i078c').setStyle({width:w});}};function setC(v,c,a){var id='i078'+a;if(!v){v=0;}
if(!c){c="#"+mcval;}
if(isNaN(v)){$(id).style.border=v+" solid "+c;}else{$(id).style.border=v+"px solid "+c;}};function bDis(){setC(dyn.bdc.v[10],dyn.bdc.c[10],'c');setC(dyn.bdc.v[11],dyn.bdc.c[11],'d');setC(dyn.bdc.v[12],dyn.bdc.c[12],'e');};function rbDis(){setBG($('i078e'),dyn.bdc.c[15]);}
function nzV(){var bb=dyn.bdc.v[10];var pp=dyn.bdc.v[11];var ee=dyn.bdc.v[12];$('newSize').value=parseInt($('i078').width)+(2*parseInt(bb))+(2*parseInt(pp))+(2*parseInt(ee));};function hideP(e){window.clearTimeout(pG.tID);var x=$('Htc0');if(isv(x))var y=x.parentNode.removeChild(x);if(isv(e))bub(e);};function setCVal(x){var i,n=cpI.length;for(i=0;i<n;i++){var j=cpI[i];var c=x.c[j];var v=x.v[j];if(isv(c)){var vel=bpID(j);var cel=bID(j);if(isv($(vel))){$(vel).value=v;}
if(isv($(cel))){if(FFC){c=stripRGB(c);}
$(dyn.bfid[j]).value=c;setBG($(cel),c);}}}};function getCVal(){var v=0,i,n=cpI.length;for(i=0;i<n;i++){var j=cpI[i];var co=dyn.bdo.c[j];var vo=dyn.bdo.v[j];if((isv(co))&&(isv(vo))){var vel=bpID(j);v=vpal1($(vel),false);if(v>=0){dyn.bdc.v[j]=v;}
var cel=bID(j);dyn.bdc.c[j]=getBG($(cel));}}};function whoC(i){if((i=='bc10')||(i=='bc11')||(i=='bc12')||(i=='bc14')||(i=='bc15'))return $(i+'a');return false;};function whoCP(){return $('Htc0').parentNode;};function sC01(){if((dyn.bdc.v[10]==0)&&(dyn.bdc.v[11]==0)&&(dyn.bdc.v[12]==0)){var j,n=cpI.length,x=false;for(i=0;i<n;i++){j=cpI[i];if((j!=14)&&(j!=15)){dyn.bdc.c[j]=dyn.bdd.c[j];dyn.bdc.v[j]=dyn.bdd.v[j];}}}}
function sC02(i){var n=geti(i);if(dyn.bdc.v[n]==0){var el=bpID(n);var v=dyn.bdd.v[n];$(el).value=v;dyn.bdc.v[n]=v;}}
function eBPre1(){Event.observe($('cd5'),'click',preV);};function eBPre2(){Event.observe($('bbpr'),'click',preV);};function eBNo(){Event.observe($('i6'),'click',stOv);};function bSh8(x){if(x){Event.observe($('ccb8'),'click',c776);}else{Event.stopObserving($('ccb8'),'click',c776);}};function bKup(){Event.observe($('bp10'),'keyup',bball);Event.observe($('bp11'),'keyup',bball);Event.observe($('bp12'),'keyup',bball);};function rK(){Event.observe($('bp15'),'keyup',brall);}
function cfun(){Event.observe($('cb4'),'click',c779);Event.observe($('cbf'),'click',c778);};function cset(){Event.observe($('cd99'),'keyup',cropKU);Event.observe($('cd98'),'keyup',cropKD);Event.observe($('cd94'),'click',eCrat);}
function bP9(){if(IE6){Event.observe($('Htc0'),'click',bChg);Event.observe($('Htc0'),'mouseleave',bOut);Event.observe($('Htc0'),'mouseover',bOver);}};function bSw7(){var n=cpI.length;for(i=0;i<n;i++){var j=cpI[i];var v=bID(j);if($(v)){swE(v);if(j==15)pG.re_ie=true;if(j==10)pG.be_ie=true;}}};function bSw8(){swE(bID(10));swE(bID(11));swE(bID(12));};function eup(){var na56="<img src='lib/styles/a1.gif' height='11' width='45' align='absmiddle' style='padding-right:3px'/>";if(OPR)na56="<img src='lib/styles/a1.gif' height='11' width='45' style='padding-right:3px'/>";if(IE8)na56="<img src='lib/styles/a1.gif' height='11' width='45' align='absmiddle' style='padding-right:3px;padding-bottom:6px;'/>";Event.observe($('i4'),'click',function(){$('um7').innerHTML=na56+na56+"<span class='um9'>"+lmsg1+"</span>";});};function preV(e){var p=inp();if(!p){hideP(e);dcp();if(cv){scr2();}
var i=$('i078');i.parentNode.replaceChild(dyn.bi,i);bHall(false);showP();getCVal();if(!pG.r){sC01();}
bUP();setCVal(dyn.bdc);if(!pG.r){bDis();setDimC();addbe();nzV();}else{rbDis();roundp();}
icd();}};function stOv(){icw();zbv();};function zbv(){$('bp10').value=0;$('bp11').value=0;$('bp12').value=0;};function zb(){setC(0,'#'+lcval,'c');setC(0,'#'+lcval,'d');setC(0,'#'+lcval,'e');};function c776(){icw();$('undoBorder').value=1;zbv();getCVal();nzV();document.iform.submit();return false;};function clickP(e){hideP(e);dcp();icw();showO();$('i078').parentNode.replaceChild(dyn.i,$('i078'));if(dyn.rt){var tt=0;}
zb();bHall(true);bDown();if(dyn.rt){roundit();}else{squareit();}
setCVal(dyn.bdo);getCVal();if(pG.r){if(FFC)swE(bID(15));}else{if(FFC)bSw8();}
eBPre1();cfun();$('newSize').value=$('i078').width;resetDimC();icd();};function bball(e){var a=this.id;if(!isv(a)){a=$(Event.element(event)).id;}
var v=geti(a);var b='bc'+v;var d='c';if(v==12)d='e';if(v==11)d='d';var v=vpal1($(a),true);if(v>=0){var c=getBG($(b));setC(v,c,d);getCVal();setDimC();nzV();return;}else{return;}}
function brall(){dor(false);}
function addbe(){bSw8();bSh8(true);bKup();};function c779(){this.blur;scr();}
function c778(){this.blur;sfz();}
function setCrop0(){var a,b,ra,rb;var ox1=parseInt($('x1').value,10);var oy1=parseInt($('y1').value,10);if(ob('w')){ox1=0;if(ob('w',true)){$('cd98').value=$('i078').width;}}
if(ob('h')){oy1=0;if(ob('h',true)){$('cd99').value=$('i078').height;}}
if($('in1').checked==true)$('newSize').value=$('cd98').value;else $('newSize').value=('cd99').value;if($('cd99').value=='')b=0;else{b=$('cd99').value;}
if($('cd98').value=='')a=0;else{a=$('cd98').value;}
if($('cd94').checked==true){ra=a;rb=b;setLock('cr88',true);}else{ra=0;rb=0;setLock('cr88',false);}
xxa.x1=ox1;xxa.y1=oy1;xxa.x2=xxa.x1+parseInt(a,10);xxa.y2=xxa.y1+parseInt(b,10);rcr();mc=new Cropper.Img('i078',{ratioDim:{x:ra,y:rb},onEndCrop:onEndCrop,displayOnInit:true,onloadCoords:{x1:xxa.x1,y1:xxa.y1,x2:xxa.x2,y2:xxa.y2}});};function cropKU(){var x=$('cd99');if(x.value.match(/[^0123456789]/g)){x.style.color="red";return;}
else{x.style.color="black";setCrop0();}};function cropKD(){var x=$('cd98');if(x.value.match(/[^0123456789]/g)){x.style.color="red";}
else{x.style.color="black";setCrop0();}};function eCrat(e){setCrop0();};function setLock(i,s){var x=$(i);if(isv(x)){if(s==true){x.setStyle({backgroundImage:'url(lib/styles/ratio_on.gif)'});}else if(s==false){x.setStyle({backgroundImage:'url(lib/styles/ratio.gif)'});}};}
function swE(i){var el=$(i);if(isv(el)){if(IE6){Event.observe(el,'click',bCol);Event.observe(el,'mouseleave',bOut);}else{Event.observe(el,'click',cpSh);}}};function bChg(e){window.clearTimeout(pG.tID);var t=Event.element(e);if(t.tagName){if(t.tagName=='DIV'){var c=getBG($(t.id));var p=whoCP();if(FFC){c=stripRGB(c);}
var b=false,r=false;if(p.id=='bc10a'){setBG($('bc10'),c);$('bColor').value=c;b=true;}else if(p.id=='bc11a'){setBG($('bc11'),c);$('pColor').value=c;b=true;}else if(p.id=='bc12a'){setBG($('bc12'),c);$('eColor').value=c;b=true;}else if(p.id=='bc14a'){setBG($('bc14'),c);$('tColor').value=c;}else if(p.id=='bc15a'){setBG($('bc15'),c);$('gColor').value=c;r=true;}else{return;}
if(inp()){getCVal();if(b){sC02(p.id);setDimC();bDis();}
if(r){rbDis();}}}}
bub(e);};function bOut(e){window.clearTimeout(pG.tID);pG.tID=window.setTimeout(hideP,1000);bub(e);};function bOver(e){window.clearTimeout(pG.tID);bub(e);};function bCol(e){window.clearTimeout(pG.tID);var t=Event.element(e);if(cpd()){cpSh(e);bub(e);return false;};if(isv($('Htc0'))){if(t.id){var p=whoCP();var pn=geti(p.id);var tn=geti(t.id);if(pn!=tn){showB(e);bub(e);return false;}else if(pn==tn){hideP(e);bub(e);return false;}}}else{showB(e);}
bub(e);return false;};function showB(e){window.clearTimeout(pG.tID);var t=Event.element(e);if(t.id){var i=whoC(t.id);if(!isv(i)){bub(e);return;}}else{bub(e);return;}
var ph='113';if(IE7&&!IE8)ph='101';if(IE6)ph='102';var sh='23';if(!IE6&&!IE7)sh=$(t.id).getHeight();var y=$('Htc0');if(isv(y))var q=y.parentNode.removeChild(y);var isup=inp();if((isup)&&(t.id!='bc14')){i.style.top=sh+'px';}else{i.style.top='-'+ph+'px';}
y=stat.cw.cloneNode(true);q=i.appendChild(y);bP9();bub(e);};function cpal0(e){hideP(e);}
function ob(d,m){if(d=='w'){var n=parseInt($('i078').width,10);if(m)var o=0;else var o=parseInt($('x1').value,10);var s=parseInt($('cd98').value,10);}else{var n=parseInt($('i078').height,10);if(m)var o=0;else var o=parseInt($('y1').value,10);var s=parseInt($('cd99').value,10);}if((o+s)>n)return true;else return false;}
function ept(){this.x1=0;this.x2=0;this.y1=0;this.y2=0;}
var CropDraggable=Class.create();var Cropper={};function gpc(){Object.extend(Object.extend(CropDraggable.prototype,Draggable.prototype),{initialize:function(_1){this.options=Object.extend({drawMethod:function(){}},arguments[1]||{});this.element=$(_1);this.handle=this.element;this.delta=this.currentDelta();this.dragging=false;this.eventMouseDown=this.initDrag.bindAsEventListener(this);Event.observe(this.handle,"mousedown",this.eventMouseDown);Draggables.register(this);},draw:function(_2){var _3=Position.cumulativeOffset(this.element);var d=this.currentDelta();_3[0]-=d[0];_3[1]-=d[1];var p=[0,1].map(function(i){return(_2[i]-_3[i]-this.offset[i]);}.bind(this));this.options.drawMethod(p);}});Cropper.Img=Class.create();Cropper.Img.prototype={initialize:function(_7,_8){this.options=Object.extend({ratioDim:{x:0,y:0},minWidth:0,minHeight:0,displayOnInit:false,onEndCrop:Prototype.emptyFunction,captureKeys:true,onloadCoords:null,maxWidth:0,maxHeight:0},_8||{});this.img=$(_7);this.clickCoords={x:0,y:0};this.dragging=false;this.resizing=false;this.isWebKit=/Konqueror|Safari|KHTML/.test(navigator.userAgent);this.isIE=/MSIE/.test(navigator.userAgent);this.isOpera8=/Opera\s[1-8]/.test(navigator.userAgent);this.ratioX=0;this.ratioY=0;this.attached=false;this.fixedWidth=(this.options.maxWidth>0&&(this.options.minWidth>=this.options.maxWidth));this.fixedHeight=(this.options.maxHeight>0&&(this.options.minHeight>=this.options.maxHeight));if(typeof this.img=="undefined"){return;}
if(this.options.ratioDim.x>0&&this.options.ratioDim.y>0){var _c=this.getGCD(this.options.ratioDim.x,this.options.ratioDim.y);this.ratioX=this.options.ratioDim.x/_c;this.ratioY=this.options.ratioDim.y/_c;}
this.subInitialize();if(this.img.complete||this.isWebKit){this.onLoad();}else{Event.observe(this.img,"load",this.onLoad.bindAsEventListener(this));}},getGCD:function(a,b){if(b==0){return a;}
return this.getGCD(b,a%b);},onLoad:function(){var _f="imgCrop_";var _10=this.img.parentNode;var _11="";if(this.isOpera8){_11=" opera8";}
this.imgWrap=Builder.node("div",{"class":_f+"wrap"+_11});this.north=Builder.node("div",{"class":_f+"overlay "+_f+"north"},[Builder.node("span")]);this.east=Builder.node("div",{"class":_f+"overlay "+_f+"east"},[Builder.node("span")]);this.south=Builder.node("div",{"class":_f+"overlay "+_f+"south"},[Builder.node("span")]);this.west=Builder.node("div",{"class":_f+"overlay "+_f+"west"},[Builder.node("span")]);var _12=[this.north,this.east,this.south,this.west];this.dragArea=Builder.node("div",{"class":_f+"dragArea"},_12);this.handleN=Builder.node("div",{"class":_f+"handle "+_f+"handleN"});this.handleNE=Builder.node("div",{"class":_f+"handle "+_f+"handleNE"});this.handleE=Builder.node("div",{"class":_f+"handle "+_f+"handleE"});this.handleSE=Builder.node("div",{"class":_f+"handle "+_f+"handleSE"});this.handleS=Builder.node("div",{"class":_f+"handle "+_f+"handleS"});this.handleSW=Builder.node("div",{"class":_f+"handle "+_f+"handleSW"});this.handleW=Builder.node("div",{"class":_f+"handle "+_f+"handleW"});this.handleNW=Builder.node("div",{"class":_f+"handle "+_f+"handleNW"});this.selArea=Builder.node("div",{"class":_f+"selArea"},[Builder.node("div",{"class":_f+"marqueeHoriz "+_f+"marqueeNorth"},[Builder.node("span")]),Builder.node("div",{"class":_f+"marqueeVert "+_f+"marqueeEast"},[Builder.node("span")]),Builder.node("div",{"class":_f+"marqueeHoriz "+_f+"marqueeSouth"},[Builder.node("span")]),Builder.node("div",{"class":_f+"marqueeVert "+_f+"marqueeWest"},[Builder.node("span")]),this.handleN,this.handleNE,this.handleE,this.handleSE,this.handleS,this.handleSW,this.handleW,this.handleNW,Builder.node("div",{"class":_f+"clickArea"})]);this.imgWrap.appendChild(this.img);this.imgWrap.appendChild(this.dragArea);this.dragArea.appendChild(this.selArea);this.dragArea.appendChild(Builder.node("div",{"class":_f+"clickArea"}));_10.appendChild(this.imgWrap);this.startDragBind=this.startDrag.bindAsEventListener(this);Event.observe(this.dragArea,"mousedown",this.startDragBind);this.onDragBind=this.onDrag.bindAsEventListener(this);Event.observe(document,"mousemove",this.onDragBind);this.endCropBind=this.endCrop.bindAsEventListener(this);Event.observe(document,"mouseup",this.endCropBind);this.resizeBind=this.startResize.bindAsEventListener(this);this.handles=[this.handleN,this.handleNE,this.handleE,this.handleSE,this.handleS,this.handleSW,this.handleW,this.handleNW];this.registerHandles(true);if(this.options.captureKeys){this.keysBind=this.handleKeys.bindAsEventListener(this);Event.observe(document,"keypress",this.keysBind);}
new CropDraggable(this.selArea,{drawMethod:this.moveArea.bindAsEventListener(this)});this.setParams();},registerHandles:function(_13){for(var i=0;i<this.handles.length;i++){var _15=$(this.handles[i]);if(_13){var _16=false;if(this.fixedWidth&&this.fixedHeight){_16=true;}else{if(this.fixedWidth||this.fixedHeight){var _17=_15.className.match(/([S|N][E|W])$/);var _18=_15.className.match(/(E|W)$/);var _19=_15.className.match(/(N|S)$/);if(_17){_16=true;}else{if(this.fixedWidth&&_18){_16=true;}else{if(this.fixedHeight&&_19){_16=true;}}}}}
if(_16){_15.hide();}else{Event.observe(_15,"mousedown",this.resizeBind);}}else{_15.show();Event.stopObserving(_15,"mousedown",this.resizeBind);}}},setParams:function(){this.imgW=this.img.width;this.imgH=this.img.height;$(this.north).setStyle({height:0});$(this.east).setStyle({width:0,height:0});$(this.south).setStyle({height:0});$(this.west).setStyle({width:0,height:0});$(this.imgWrap).setStyle({"width":this.imgW+"px","height":this.imgH+"px"});$(this.selArea).hide();var _1a={x1:0,y1:0,x2:0,y2:0};var _1b=false;if(this.options.onloadCoords!=null){_1a=this.cloneCoords(this.options.onloadCoords);_1b=true;}else{if(this.options.ratioDim.x>0&&this.options.ratioDim.y>0){_1a.x1=Math.ceil((this.imgW-this.options.ratioDim.x)/2);_1a.y1=Math.ceil((this.imgH-this.options.ratioDim.y)/2);_1a.x2=_1a.x1+this.options.ratioDim.x;_1a.y2=_1a.y1+this.options.ratioDim.y;_1b=true;}}
this.setAreaCoords(_1a,false,false,1);if(this.options.displayOnInit&&_1b){this.selArea.show();this.drawArea();this.endCrop();}
this.attached=true;},remove:function(){if(this.attached){this.attached=false;this.imgWrap.parentNode.insertBefore(this.img,this.imgWrap);this.imgWrap.parentNode.removeChild(this.imgWrap);Event.stopObserving(this.dragArea,"mousedown",this.startDragBind);Event.stopObserving(document,"mousemove",this.onDragBind);Event.stopObserving(document,"mouseup",this.endCropBind);this.registerHandles(false);if(this.options.captureKeys){Event.stopObserving(document,"keypress",this.keysBind);}}},reset:function(){if(!this.attached){this.onLoad();}else{this.setParams();}
this.endCrop();},handleKeys:function(e){var dir={x:0,y:0};if(!this.dragging){switch(e.keyCode){case(37):dir.x=-1;break;case(38):dir.y=-1;break;case(39):dir.x=1;break;case(40):dir.y=1;break;}
if(dir.x!=0||dir.y!=0){if(e.shiftKey){dir.x*=10;dir.y*=10;}
this.moveArea([this.areaCoords.x1+dir.x,this.areaCoords.y1+dir.y]);Event.stop(e);}}},calcW:function(){return(this.areaCoords.x2-this.areaCoords.x1);},calcH:function(){return(this.areaCoords.y2-this.areaCoords.y1);},moveArea:function(_1e){this.setAreaCoords({x1:_1e[0],y1:_1e[1],x2:_1e[0]+this.calcW(),y2:_1e[1]+this.calcH()},true,false);this.drawArea();},cloneCoords:function(_1f){return{x1:_1f.x1,y1:_1f.y1,x2:_1f.x2,y2:_1f.y2};},setAreaCoords:function(_20,_21,_22,_23,_24){if(_21){var _25=_20.x2-_20.x1;var _26=_20.y2-_20.y1;if(_20.x1<0){_20.x1=0;_20.x2=_25;}
if(_20.y1<0){_20.y1=0;_20.y2=_26;}
if(_20.x2>this.imgW){_20.x2=this.imgW;_20.x1=this.imgW-_25;}
if(_20.y2>this.imgH){_20.y2=this.imgH;_20.y1=this.imgH-_26;}}else{if(_20.x1<0){_20.x1=0;}
if(_20.y1<0){_20.y1=0;}
if(_20.x2>this.imgW){_20.x2=this.imgW;}
if(_20.y2>this.imgH){_20.y2=this.imgH;}
if(_23!=null){if(this.ratioX>0){this.applyRatio(_20,{x:this.ratioX,y:this.ratioY},_23,_24);}else{if(_22){this.applyRatio(_20,{x:1,y:1},_23,_24);}}
var _27=[this.options.minWidth,this.options.minHeight];var _28=[this.options.maxWidth,this.options.maxHeight];if(_27[0]>0||_27[1]>0||_28[0]>0||_28[1]>0){var _29={a1:_20.x1,a2:_20.x2};var _2a={a1:_20.y1,a2:_20.y2};var _2b={min:0,max:this.imgW};var _2c={min:0,max:this.imgH};if((_27[0]!=0||_27[1]!=0)&&_22){if(_27[0]>0){_27[1]=_27[0];}else{if(_27[1]>0){_27[0]=_27[1];}}}
if((_28[0]!=0||_28[0]!=0)&&_22){if(_28[0]>0&&_28[0]<=_28[1]){_28[1]=_28[0];}else{if(_28[1]>0&&_28[1]<=_28[0]){_28[0]=_28[1];}}}
if(_27[0]>0){this.applyDimRestriction(_29,_27[0],_23.x,_2b,"min");}
if(_27[1]>1){this.applyDimRestriction(_2a,_27[1],_23.y,_2c,"min");}
if(_28[0]>0){this.applyDimRestriction(_29,_28[0],_23.x,_2b,"max");}
if(_28[1]>1){this.applyDimRestriction(_2a,_28[1],_23.y,_2c,"max");}
_20={x1:_29.a1,y1:_2a.a1,x2:_29.a2,y2:_2a.a2};}}}
this.areaCoords=_20;},applyDimRestriction:function(_2d,val,_2f,_30,_31){var _32;if(_31=="min"){_32=((_2d.a2-_2d.a1)<val);}else{_32=((_2d.a2-_2d.a1)>val);}
if(_32){if(_2f==1){_2d.a2=_2d.a1+val;}else{_2d.a1=_2d.a2-val;}
if(_2d.a1<_30.min){_2d.a1=_30.min;_2d.a2=val;}else{if(_2d.a2>_30.max){_2d.a1=_30.max-val;_2d.a2=_30.max;}}}},applyRatio:function(_33,_34,_35,_36){var _37;if(_36=="N"||_36=="S"){_37=this.applyRatioToAxis({a1:_33.y1,b1:_33.x1,a2:_33.y2,b2:_33.x2},{a:_34.y,b:_34.x},{a:_35.y,b:_35.x},{min:0,max:this.imgW});_33.x1=_37.b1;_33.y1=_37.a1;_33.x2=_37.b2;_33.y2=_37.a2;}else{_37=this.applyRatioToAxis({a1:_33.x1,b1:_33.y1,a2:_33.x2,b2:_33.y2},{a:_34.x,b:_34.y},{a:_35.x,b:_35.y},{min:0,max:this.imgH});_33.x1=_37.a1;_33.y1=_37.b1;_33.x2=_37.a2;_33.y2=_37.b2;}},applyRatioToAxis:function(_38,_39,_3a,_3b){var _3c=Object.extend(_38,{});var _3d=_3c.a2-_3c.a1;var _3e=Math.floor(_3d*_39.b/_39.a);var _3f;var _40;var _41=null;if(_3a.b==1){_3f=_3c.b1+_3e;if(_3f>_3b.max){_3f=_3b.max;_41=_3f-_3c.b1;}
_3c.b2=_3f;}else{_3f=_3c.b2-_3e;if(_3f<_3b.min){_3f=_3b.min;_41=_3f+_3c.b2;}
_3c.b1=_3f;}
if(_41!=null){_40=Math.floor(_41*_39.a/_39.b);if(_3a.a==1){_3c.a2=_3c.a1+_40;}else{_3c.a1=_3c.a1=_3c.a2-_40;}}
return _3c;},drawArea:function(){var _42=this.calcW();var _43=this.calcH();var px="px";var _45=[this.areaCoords.x1+px,this.areaCoords.y1+px,_42+px,_43+px,this.areaCoords.x2+px,this.areaCoords.y2+px,(this.img.width-this.areaCoords.x2)+px,(this.img.height-this.areaCoords.y2)+px];var _46=this.selArea.style;_46.left=_45[0];_46.top=_45[1];_46.width=_45[2];_46.height=_45[3];var _47=Math.ceil((_42-6)/2)+px;var _48=Math.ceil((_43-6)/2)+px;this.handleN.style.left=_47;this.handleE.style.top=_48;this.handleS.style.left=_47;this.handleW.style.top=_48;this.north.style.height=_45[1];var _49=this.east.style;_49.top=_45[1];_49.height=_45[3];_49.left=_45[4];_49.width=_45[6];var _4a=this.south.style;_4a.top=_45[5];_4a.height=_45[7];var _4b=this.west.style;_4b.top=_45[1];_4b.height=_45[3];_4b.width=_45[0];this.subDrawArea();this.forceReRender();},forceReRender:function(){if(this.isIE||this.isWebKit){var n=document.createTextNode(" ");var d,el,fixEL,i;if(this.isIE){fixEl=this.selArea;}else{if(this.isWebKit){fixEl=document.getElementsByClassName("imgCrop_marqueeSouth",this.imgWrap)[0];d=Builder.node("div","");d.style.visibility="hidden";var _4e=["SE","S","SW"];for(i=0;i<_4e.length;i++){el=document.getElementsByClassName("imgCrop_handle"+_4e[i],this.selArea)[0];if(el.childNodes.length){el.removeChild(el.childNodes[0]);}
el.appendChild(d);}}}
fixEl.appendChild(n);fixEl.removeChild(n);}},startResize:function(e){this.startCoords=this.cloneCoords(this.areaCoords);this.resizing=true;this.resizeHandle=Event.element(e).classNames().toString().replace(/([^N|NE|E|SE|S|SW|W|NW])+/,"");Event.stop(e);},startDrag:function(e){this.selArea.show();this.clickCoords=this.getCurPos(e);this.setAreaCoords({x1:this.clickCoords.x,y1:this.clickCoords.y,x2:this.clickCoords.x,y2:this.clickCoords.y},false,false,null);this.dragging=true;this.onDrag(e);Event.stop(e);},getCurPos:function(e){var el=this.imgWrap,wrapOffsets=Position.cumulativeOffset(el);while(el.nodeName!="BODY"){wrapOffsets[1]-=el.scrollTop||0;wrapOffsets[0]-=el.scrollLeft||0;el=el.parentNode;}
return curPos={x:Event.pointerX(e)-wrapOffsets[0],y:Event.pointerY(e)-wrapOffsets[1]};},onDrag:function(e){if(this.dragging||this.resizing){var _54=null;var _55=this.getCurPos(e);var _56=this.cloneCoords(this.areaCoords);var _57={x:1,y:1};if(this.dragging){if(_55.x<this.clickCoords.x){_57.x=-1;}
if(_55.y<this.clickCoords.y){_57.y=-1;}
this.transformCoords(_55.x,this.clickCoords.x,_56,"x");this.transformCoords(_55.y,this.clickCoords.y,_56,"y");}else{if(this.resizing){_54=this.resizeHandle;if(_54.match(/E/)){this.transformCoords(_55.x,this.startCoords.x1,_56,"x");if(_55.x<this.startCoords.x1){_57.x=-1;}}else{if(_54.match(/W/)){this.transformCoords(_55.x,this.startCoords.x2,_56,"x");if(_55.x<this.startCoords.x2){_57.x=-1;}}}
if(_54.match(/N/)){this.transformCoords(_55.y,this.startCoords.y2,_56,"y");if(_55.y<this.startCoords.y2){_57.y=-1;}}else{if(_54.match(/S/)){this.transformCoords(_55.y,this.startCoords.y1,_56,"y");if(_55.y<this.startCoords.y1){_57.y=-1;}}}}}
this.setAreaCoords(_56,false,e.shiftKey,_57,_54);this.drawArea();if($('cd94').checked!=true){var x99=this.calcH();var c9=$('cd99');c9.value=x99;var xl5=this.calcW();var c8=$('cd98');c8.value=xl5;c9.style.color="black";c8.style.color="black";}
Event.stop(e);}},transformCoords:function(_58,_59,_5a,_5b){var _5c=[_58,_59];if(_58>_59){_5c.reverse();}
_5a[_5b+"1"]=_5c[0];_5a[_5b+"2"]=_5c[1];},endCrop:function(){this.dragging=false;this.resizing=false;this.options.onEndCrop(this.areaCoords,{width:this.calcW(),height:this.calcH()});},subInitialize:function(){},subDrawArea:function(){}};Cropper.ImgWithPreview=Class.create();Object.extend(Object.extend(Cropper.ImgWithPreview.prototype,Cropper.Img.prototype),{subInitialize:function(){this.hasPreviewImg=false;if(typeof(this.options.previewWrap)!="undefined"&&this.options.minWidth>0&&this.options.minHeight>0){this.previewWrap=$(this.options.previewWrap);this.previewImg=this.img.cloneNode(false);this.previewImg.id="imgCrop_"+this.previewImg.id;this.options.displayOnInit=true;this.hasPreviewImg=true;this.previewWrap.addClassName("imgCrop_previewWrap");this.previewWrap.setStyle({width:this.options.minWidth+"px",height:this.options.minHeight+"px"});this.previewWrap.appendChild(this.previewImg);}},subDrawArea:function(){if(this.hasPreviewImg){var _5d=this.calcW();var _5e=this.calcH();var _5f={x:this.imgW/_5d,y:this.imgH/_5e};var _60={x:_5d/this.options.minWidth,y:_5e/this.options.minHeight};var _61={w:Math.ceil(this.options.minWidth*_5f.x)+"px",h:Math.ceil(this.options.minHeight*_5f.y)+"px",x:"-"+Math.ceil(this.areaCoords.x1/_60.x)+"px",y:"-"+Math.ceil(this.areaCoords.y1/_60.y)+"px"};var _62=this.previewImg.style;_62.width=_61.w;_62.height=_61.h;_62.left=_61.x;_62.top=_61.y;}}});}
function roundp(){Von($('ccb8'),false);zb();$('newSize').value=dyn.bi.width;dor(true);rbDis();rK();swE(bID(15));pG.pr_ie=true;}
function roundit(){if(!pG.r){pG.r=true;dcp();hideP();roundLoad();if(inp()){roundp();bSh8(false);}
else{if(FFC||!pG.re_ie){swE(bID(15));pG.re_ie=true;}}}}
function roundLoad(){var b=$('bb2');dyn.bn=b.cloneNode(true);getCVal(dyn.bdc);var g=b.parentNode.replaceChild(dyn.rtn,b);}
function squareit(){if(pG.r){pG.r=false;dcp();hideP();var b=$('bb2');dyn.rtn=b.cloneNode(true);b.parentNode.replaceChild(dyn.bn,b);setCVal(dyn.bdc);if(inp()){$('i078').parentNode.replaceChild(dyn.bi,$('i078'));setBG($('i078e'),dyn.rbc);bDis();setDimC();nzV();Von($('ccb8'),true);addbe();}else{Event.stopObserving($('bp10'),'keyup',bball);Event.stopObserving($('bp11'),'keyup',bball);Event.stopObserving($('bp12'),'keyup',bball);bSw8();}}}
function dor(x){var r=$('bp15');if(isv(r))r=r.value;else r=pG.ro;var v=vpal1($('bp15'),true);if(v==-1){if(x)r=pG.ro;else return;}
var h=dyn.bi.height;var w=dyn.bi.width;var n=dyn.rn.cloneNode(true);var mr=Math.min(Math.ceil((Math.min(h,w)-3)/2),r);if(x){if(mr==0)mr=pG.ro;$('bp15').value=mr;if(pG.br){$('i078').parentNode.replaceChild(n,$('i078'));}
var rh=dyn.bi.height+'px';var rw=dyn.bi.width+'px';$('i078e').setStyle({height:rh,width:rw});}
if(!pG.br){var i=$('i078');rst.init(mr);if(OPR){var d='Hz8';var h=$(d);var n=dyn.rn.cloneNode(true);n.id=d;h.parentNode.replaceChild(n,h);curvyCorners(rst.rs,"#"+d);h=$(d).cloneNode(true);h.id='i078';$('i078').parentNode.replaceChild(h,$('i078'));var x=stat.en.cloneNode(true);x.id=d;$(d).parentNode.replaceChild(x,$(d));}else{i.parentNode.replaceChild(n,i);curvyCorners(rst.rs,"#i078");}}
else{var i=$('i078');var p=mr+'px';i.style.MozBorderRadius=p;i.style.borderRadius=p;i.style.WebkitBorderRadius=p;i.style.KhtmlBorderRadius=p;}}
Event.observe(window,'load',function(){iDynam();icd();img2=new Image();img3=new Image();img2.src="lib/styles/ratio_on.gif";img3.src="lib/styles/SatVal.png";});Event.observe(window,'unload',function(){icw();});var _original_onselectstart=document.onselectstart;function enableSelection(enable){if(OPR){return;}
if(document.onselectstart!='undefined'){if(enable){document.onselectstart=_original_onselectstart;}
else{_original_onselectstart=document.onselectstart;document.onselectstart=function(){return false;}}}
else{var a=false;}};var maxValue={'h':360,'s':100,'v':100},HSV={0:360,1:100,2:100};var hSV=165,wSV=162,hH=163,slideHSV={0:360,1:100,2:100},zINDEX=15,stop=1;function $S(v){return($(v).style);};function absPos(o){var r={x:o.offsetLeft,y:o.offsetTop};if(o.offsetParent){var v=absPos(o.offsetParent);r.x+=v.x;r.y+=v.y;}return(r);};function agent(v){return(Math.max(navigator.userAgent.toLowerCase().indexOf(v),0));};function toggle(v){$S(v).display=($S(v).display=='none'?'block':'none');};function within(v,a,z){return((v>=a&&v<=z)?true:false);};function XY(e,v){var z=agent('msie')?[event.clientX+document.documentElement.scrollLeft,event.clientY+document.documentElement.scrollTop]:[e.pageX,e.pageY];return(z[zero(v)]);};function XYwin(v){var z=agent('msie')?[document.body.clientHeight,document.body.clientWidth]:[window.innerHeight,window.innerWidth];return(!isNaN(v)?z[v]:z);};function zero(v){v=parseInt(v);return(!isNaN(v)?v:0);};function cPoint(hsv){function ckHSV(a,b){if(within(a,0,b))return(a);else if(a>b)return(b);else if(a<0)return('-'+oo);}
function mkHSV(a,b,c){return(Math.min(a,Math.max(0,Math.ceil((parseInt(c)/b)*a))));}
var d='SVslide';var oo=4;var v=$S(d);var s=$S('Hslide');var t=Math.ceil(162-(hsv[2]*162));var t2=0;var l=Math.ceil(hsv[1]*162);x=((360-hsv[0])/360);var h=Math.ceil(x*163);v.top=t+"px";v.left=l+"px";var j,r='hsv',z={};var sh=(parseInt(h));if(sh>157)s.top='157px';else s.top=sh+'px';$S('SV').backgroundColor='#'+hsv2hex([hsv[0],100,100]);HSV[0]=hsv[0];HSV[1]=Math.ceil(hsv[1]*100);HSV[2]=Math.ceil(hsv[2]*100);};function HSVslide(d,o,e){function tXY(e){tY=XY(e,1)-ab.y;tX=XY(e)-ab.x;}
function mkHSV(a,b,c){return(Math.min(a,Math.max(0,Math.ceil((parseInt(c)/b)*a))));}
function ckHSV(a,b){if(within(a,0,b))return(a);else if(a>b)return(b);else if(a<0)return('-'+oo);}
function drag(e){if(!stop){if(d!='drag')tXY(e);if(d=='SVslide'){ds.left=ckHSV(tX-oo,wSV)+'px';ds.top=ckHSV(tY-oo,wSV)+'px';slideHSV[1]=mkHSV(100,wSV,ds.left);slideHSV[2]=100-mkHSV(100,wSV,ds.top);HSVupdate();}
else if(d=='Hslide'){var ck=ckHSV(tY-oo,hH),j,r='hsv',z={};ds.top=(ck-5)+'px';slideHSV[0]=mkHSV(360,hH,ck);for(var i=0;i<=r.length-1;i++){j=r.substr(i,1);z[i]=(j=='h')?maxValue[j]-mkHSV(maxValue[j],hH,ck):HSV[i];}
HSVupdate(z);$S('SV').backgroundColor='#'+hsv2hex([HSV[0],100,100]);if(!e)var e=window.event;if(isv(e)){e.cancelBubble=true;if(e.stopPropagation)e.stopPropagation();}}
else if(d=='drag'){if(!OPR){var nL=XY(e)+oX-eX;var nT=XY(e,1)+oY-eY;if(ina==true){var Bh=pG.vh-(parseInt(nT));if((Bh>0)&&(nT>=0)){ds.top=nT+'px';}
var Bw=pG.vw-(parseInt(nL)+220);if((Bw>0)&&(nL>=0)){ds.left=nL+'px';}}else{ds.top=nT+'px';ds.left=nL+'px';}}}}}
if(stop){stop='';var ds=$S(d!='drag'?d:o);if(d=='drag'){var oX=parseInt(ds.left),oY=parseInt(ds.top),eX=XY(e),eY=XY(e,1);$S(o).zIndex=zINDEX++;}
else{var ab=absPos($(o)),tX,tY,oo=(d=='Hslide')?2:4;ab.x+=10;ab.y+=22;if(d=='SVslide')slideHSV[0]=HSV[0];}
document.onmousemove=drag;document.onmouseup=function(){stop=1;document.onmousemove='';document.onmouseup='';};drag(e);}};function HSVupdate(v){v=hsv2hex(HSV=v?v:slideHSV);$('cpHEX').value=v;cpSet(v);dsw();return(v);};function hsv2hex(h){return(rgb2hex(hsv2rgb(h)));};function hsv2rgb(r){var R,B,G,S=r[1]/100,V=r[2]/100,H=r[0]/360;if(S>0){if(H>=1)H=0;H=6*H;F=H-Math.floor(H);A=Math.round(255*V*(1.0-S));B=Math.round(255*V*(1.0-(S*F)));C=Math.round(255*V*(1.0-(S*(1.0-F))));V=Math.round(255*V);switch(Math.floor(H)){case 0:R=V;G=C;B=A;break;case 1:R=B;G=V;B=A;break;case 2:R=A;G=V;B=C;break;case 3:R=A;G=B;B=V;break;case 4:R=C;G=A;B=V;break;case 5:R=V;G=A;B=B;break;}
return([R?R:0,G?G:0,B?B:0]);}
else return([(V=Math.round(V*255)),V,V]);};function cMove(W,hsv){var W2=W/2,rad=(hsv[0]/360)*(Math.PI*2),hyp=(hsv[1]+(100-hsv[2]))/100*(W2/2);$S('mCur').left=Math.round(Math.abs(Math.round(Math.sin(rad)*hyp)+W2+3))+'px';$S('mCur').top=Math.round(Math.abs(Math.round(Math.cos(rad)*hyp)-W2-21))+'px';};function RGB2HSV(r,g,b,hsv)
{var min,max,delta;r=r/255;g=g/255;b=b/255;min=Math.min(Math.min(r,g),b);max=Math.max(Math.max(r,g),b);hsv[2]=max;delta=max-min;if(max!=0)
hsv[1]=delta/max;else{hsv[1]=0;hsv[0]=-1;return;}
if(r==max)
hsv[0]=(g-b)/delta;else if(g==max)
hsv[0]=2+(b-r)/delta;else
hsv[0]=4+(r-g)/delta;if(delta==0)hsv[0]=0;hsv[0]*=60;if(hsv[0]<0)
hsv[0]+=360;hsv[3]=delta;};function toRGB(v){return Math.min(Math.max(0,parseInt(v,16)),255);};function convertN(n){var a=new Array();var hsv=new Array();hsv[0]=hsv[1]=hsv[2]=0;a[0]=toRGB(n.substr(0,2));a[1]=toRGB(n.substr(2,2));a[2]=toRGB(n.substr(4,2));RGB2HSV(a[0],a[1],a[2],hsv);return hsv;}
function convertIT(n){var hsv=convertN(n);cpSet(n);cPoint(hsv);};function cpSet(c){function cpSetV(a,c){var n=geti(a);var nc=stripRGB(c);if(nc===null)nc='#'+c;dyn.bdc.c[n]=nc;};$S('cpSwatch').backgroundColor="#"+c;cpSetV(pG.a,c);setBol('#'+c,pG.a);};function showC(){function cpGetV(a){var n=geti(a);var c="#000000";c=dyn.bdc.c[n];return stripRGB(c);};var c=cpGetV(pG.a);if(FFC){c=stripRGB(c);}
var n=geti(pG.a);dyn.bdt[n]=c;if(c.indexOf('#')!=-1){c=c.substr(1);}
$('cpHEX').value=c;convertIT(c);};function setBol(c,i){if(FFC){c=stripRGB(c);}
var n=geti(i);var j=dyn.bfid[n];if(isv(j)){setBG($(i),c);$(j).value=c;}};function zsw(v){var x=$('bc10z');if((lt.b.a==true)&&(isv(x))){if(v){$('bc10z').style.zIndex=20;$('bc11z').style.zIndex=20;$('bc12z').style.zIndex=20;}else{$('bc10z').style.zIndex=0;$('bc11z').style.zIndex=0;$('bc12z').style.zIndex=0;}}
if(lt.n.a===true){if(v)$('bc15z').style.zIndex=20;else $('bc15z').style.zIndex=10;}};function sb(){if(inp()){if(!pG.r){bDis();}else{rbDis();}}};function dsw(){getCVal();sb();};function dcp(d){var c=$('cp');if(isv(c)){if(d){c.style.display='block'}else{c.style.display='none';sO(pG.a,false);}}};function cpd(){var l=$S('cp').display;if(l=='block'){return true;}
return false;};function cpShu(i){$S('cp').left=$('i078').offsetLeft+$('iopt').offsetLeft+10+'px';$S('cp').top=pG.tp+'px';};function cpShb(i){$S('cp').left=$('i078').offsetLeft+$('iopt').offsetLeft+10+'px';$S('cp').top=pG.t+'px';};function eCP(){Event.observe($('cp'),'mousedown',cSlide);Event.observe($('SV'),'mousedown',svD);Event.observe($('H'),'mousedown',hD);Event.observe($('cpHEX'),'mousedown',bub);Event.observe($('cpHEX'),'keyup',cpIV);};function hD(e){HSVslide('Hslide','cp',e);};function svD(e){HSVslide('SVslide','cp',e);};function cSlide(e){HSVslide('drag','cp',e);};function cpIV(e){var t=Event.element(e);var x=t.value.toString();var y=parseInt(x,16);if(x.length==6){if((y<=parseInt('FFFFFF',16))&&(y>=parseInt('000000',16))){t.style.color="black";convertIT(x);return;}}
t.style.color="red";return;};function pClose(e){dcp();zsw(true);var i=geti(pG.a);var cel=bID(i);$(dyn.bfid[i]).value=dyn.bdt[i];setBG($(cel),dyn.bdt[i]);dyn.bdc.c[i]=dyn.bdt[i];sb();};function pSet(e){var i=geti(pG.a);dsw();dcp();zsw(true);};function cpV0(){$('cpki').src='lib/styles/colorp2.gif';}
function cpV1(){$('cpki').src='lib/styles/colorp.gif'}
function sO(i,a){if(isv($(i))){if(a){if(OPR&&((i=='bc14')||((i=='bc10')&&(ina)&&(!inp()))))return;$(i).style.outline="1px solid #FFCC33";}
else $(i).style.outline="none";}};function cpSh(e){function sCP(n){showC();if(inp()){if(n==14){cpShb();}
else cpShu();}else{cpShb();}
dcp(true);};var el=null,i=null;if(e=='cpk')el=$('cpk');else el=Event.element(e);if(el.id!='cpk'){i=el.id;}else{var p=whoCP();if(p){i=p.id.substr(0,4);}}
hideP(e);zsw();if(cv){scr2();}
var n=geti(i);var c=getBG($(n));var x=pG.a;pG.a=i;$('cpTit').innerHTML=cpL[n];sO(x,false);sO(i,true);if(cpd()){showC();if(n==14){cpShb();}else{if((inp())&&(x=='bc14'))cpShu();}}else{enableSelection(false);sCP(n);}
bub(e);};function browserdetect(){var agent=navigator.userAgent.toLowerCase();this.isIE=agent.indexOf("msie")>-1;this.ieVer=this.isIE?/msie\s(\d\.\d)/.exec(agent)[1]:0;this.isMoz=agent.indexOf('firefox')!=-1;this.isSafari=agent.indexOf('safari')!=-1;this.quirksMode=this.isIE&&(!document.compatMode||document.compatMode.indexOf("BackCompat")>-1);this.isOp='opera'in window;this.isWebKit=agent.indexOf('webkit')!=-1;if(this.isIE){this.get_style=function(obj,prop){if(!(prop in obj.currentStyle))return"";var matches=/^([\d.]+)(\w*)/.exec(obj.currentStyle[prop]);if(!matches)return obj.currentStyle[prop];if(matches[1]==0)return'0';if(matches[2]&&matches[2]!=='px'){var style=obj.style.left;var rtStyle=obj.runtimeStyle.left;obj.runtimeStyle.left=obj.currentStyle.left;obj.style.left=matches[1]+matches[2];matches[0]=obj.style.pixelLeft;obj.style.left=style;obj.runtimeStyle.left=rtStyle;}
return matches[0];};}
else{this.get_style=function(obj,prop){prop=prop.replace(/([a-z])([A-Z])/g,'$1-$2').toLowerCase();return document.defaultView.getComputedStyle(obj,'').getPropertyValue(prop);};}}
var curvyBrowser=new browserdetect;function curvyCnrSpec(selText){this.selectorText=selText;this.tlR=this.trR=this.blR=this.brR=0;this.tlu=this.tru=this.blu=this.bru="";this.antiAlias=true;}
curvyCnrSpec.prototype.setcorner=function(tb,lr,radius,unit){if(!tb){this.tlR=this.trR=this.blR=this.brR=parseInt(radius);this.tlu=this.tru=this.blu=this.bru=unit;}
else{propname=tb.charAt(0)+lr.charAt(0);this[propname+'R']=parseInt(radius);this[propname+'u']=unit;}}
curvyCnrSpec.prototype.get=function(prop){if(/^(t|b)(l|r)(R|u)$/.test(prop))return this[prop];if(/^(t|b)(l|r)Ru$/.test(prop)){var pname=prop.charAt(0)+prop.charAt(1);return this[pname+'R']+this[pname+'u'];}
if(/^(t|b)Ru?$/.test(prop)){var tb=prop.charAt(0);tb+=this[tb+'lR']>this[tb+'rR']?'l':'r';var retval=this[tb+'R'];if(prop.length===3&&prop.charAt(2)==='u')
retval+=this[tb='u'];return retval;}
throw new Error('Don\'t recognize property '+prop);}
curvyCnrSpec.prototype.radiusdiff=function(tb){if(tb!=='t'&&tb!=='b')throw new Error("Param must be 't' or 'b'");return Math.abs(this[tb+'lR']-this[tb+'rR']);}
curvyCnrSpec.prototype.setfrom=function(obj){this.tlu=this.tru=this.blu=this.bru='px';if('tl'in obj)this.tlR=obj.tl.radius;if('tr'in obj)this.trR=obj.tr.radius;if('bl'in obj)this.blR=obj.bl.radius;if('br'in obj)this.brR=obj.br.radius;if('antiAlias'in obj)this.antiAlias=obj.antiAlias;};curvyCnrSpec.prototype.cloneOn=function(box){var props=['tl','tr','bl','br'];var converted=0;var i,propu;for(i in props)if(!isNaN(i)){propu=this[props[i]+'u'];if(propu!==''&&propu!=='px'){converted=new curvyCnrSpec;break;}}
if(!converted)
converted=this;else{var propi,propR,save=curvyBrowser.get_style(box,'left');for(i in props)if(!isNaN(i)){propi=props[i];propu=this[propi+'u'];propR=this[propi+'R'];if(propu!=='px'){var save=box.style.left;box.style.left=propR+propu;propR=box.style.pixelLeft;box.style.left=save;}
converted[propi+'R']=propR;converted[propi+'u']='px';}
box.style.left=save;}
return converted;}
curvyCnrSpec.prototype.radiusSum=function(tb){if(tb!=='t'&&tb!=='b')throw new Error("Param must be 't' or 'b'");return this[tb+'lR']+this[tb+'rR'];}
curvyCnrSpec.prototype.radiusCount=function(tb){var count=0;if(this[tb+'lR'])++count;if(this[tb+'rR'])++count;return count;}
curvyCnrSpec.prototype.cornerNames=function(){var ret=[];if(this.tlR)ret.push('tl');if(this.trR)ret.push('tr');if(this.blR)ret.push('bl');if(this.brR)ret.push('br');return ret;}
function operasheet(sheetnumber){var txt=document.styleSheets.item(sheetnumber).ownerNode.text;txt=txt.replace(/\/\*(\n|\r|.)*?\*\//g,'');var pat=new RegExp("^\s*([\\w.#][-\\w.#, ]+)[\\n\\s]*\\{([^}]+border-((top|bottom)-(left|right)-)?radius[^}]*)\\}","mg");var matches;this.rules=[];while((matches=pat.exec(txt))!==null){var pat2=new RegExp("(..)border-((top|bottom)-(left|right)-)?radius:\\s*([\\d.]+)(in|em|px|ex|pt)","g");var submatches,cornerspec=new curvyCnrSpec(matches[1]);while((submatches=pat2.exec(matches[2]))!==null)
if(submatches[1]!=="z-")
cornerspec.setcorner(submatches[3],submatches[4],submatches[5],submatches[6]);this.rules.push(cornerspec);}}
operasheet.contains_border_radius=function(sheetnumber){return/border-((top|bottom)-(left|right)-)?radius/.test(document.styleSheets.item(sheetnumber).ownerNode.text);}
function curvyCorners(){var i,j,boxCol,settings,startIndex;j=arguments[1];if(typeof j!=='string')j='';if(j!==''&&j.charAt(0)!=='.'&&'autoPad'in arguments[0])j='.'+j;settings=new curvyCnrSpec(j);settings.setfrom(arguments[0]);if(settings.selectorText){startIndex=0;var args=settings.selectorText.replace(/\s+$/,'').split(/,\s*/);boxCol=new Array;function idof(str){var ret=str.split('#');return(ret.length===2?"#":"")+ret.pop();}
for(i=0;i<args.length;++i){var arg=idof(args[i]);var argbits=arg.split(' ');switch(arg.charAt(0)){case'#':j=argbits.length===1?arg:argbits[0];j=document.getElementById(j.substr(1));if(j===null)
curvyCorners.alert("");else if(argbits.length===1)
boxCol.push(j);else
boxCol=boxCol.concat(curvyCorners.getElementsByClass(argbits[1],j));break;default:if(argbits.length===1)
boxCol=boxCol.concat(curvyCorners.getElementsByClass(arg));else{var encloser=curvyCorners.getElementsByClass(argbits[0]);for(j=0;j<encloser.length;++j){boxCol=boxCol.concat(curvyCorners.getElementsByClass(argbits[1],encloser));}}}}}
else{startIndex=1;boxCol=arguments;}
for(i=startIndex,j=boxCol.length;i<j;++i){if(boxCol[i]&&(!('IEborderRadius'in boxCol[i].style)||boxCol[i].style.IEborderRadius!='set')){if(boxCol[i].className&&boxCol[i].className.indexOf('curvyRedraw')!==-1){if(typeof curvyCorners.redrawList==='undefined')curvyCorners.redrawList=new Array;curvyCorners.redrawList.push({node:boxCol[i],spec:settings,copy:boxCol[i].cloneNode(false)});}
boxCol[i].style.IEborderRadius='set';var obj=new curvyObject(settings,boxCol[i]);obj.applyCorners();}}}
curvyCorners.redraw=function(){if(!curvyBrowser.isOp&&!curvyBrowser.isIE)return;if(!curvyCorners.redrawList)throw curvyCorners.newError('curvyCorners.redraw() has nothing to redraw.');var old_block_value=curvyCorners.bock_redraw;curvyCorners.block_redraw=true;for(var i in curvyCorners.redrawList){if(isNaN(i))continue;var o=curvyCorners.redrawList[i];if(!o.node.clientWidth)continue;var newchild=o.copy.cloneNode(false);for(var contents=o.node.firstChild;contents!=null;contents=contents.nextSibling)
if(contents.className==='autoPadDiv')break;if(!contents){curvyCorners.alert('Couldn\'t find autoPad DIV');break;}
o.node.parentNode.replaceChild(newchild,o.node);while(contents.firstChild)newchild.appendChild(contents.removeChild(contents.firstChild));o=new curvyObject(o.spec,o.node=newchild);o.applyCorners();}
curvyCorners.block_redraw=old_block_value;}
curvyCorners.adjust=function(obj,prop,newval){if(curvyBrowser.isOp||curvyBrowser.isIE){if(!curvyCorners.redrawList)throw curvyCorners.newError('curvyCorners.adjust() has nothing to adjust.');var i,j=curvyCorners.redrawList.length;for(i=0;i<j;++i)if(curvyCorners.redrawList[i].node===obj)break;if(i===j)throw curvyCorners.newError('Object not redrawable');obj=curvyCorners.redrawList[i].copy;}
if(prop.indexOf('.')===-1)
obj[prop]=newval;else eval('obj.'+prop+"='"+newval+"'");}
curvyCorners.handleWinResize=function(){if(!curvyCorners.block_redraw)curvyCorners.redraw();}
curvyCorners.setWinResize=function(onoff){curvyCorners.block_redraw=!onoff;}
curvyCorners.newError=function(errorMessage){return;}
curvyCorners.alert=function(errorMessage){return;}
function curvyObject(){var boxDisp;this.box=arguments[1];this.settings=arguments[0];this.topContainer=this.bottomContainer=this.shell=boxDisp=null;var boxWidth=this.box.clientWidth;if(!boxWidth&&curvyBrowser.isIE){this.box.style.zoom=1;boxWidth=this.box.clientWidth;}
if(!boxWidth){for(boxDisp=this.box;;boxDisp=boxDisp.parentNode){if(!boxDisp||boxDisp.tagName==='BODY'){this.applyCorners=function(){}
return;}
if(boxDisp.style.display==='none')break;}
boxDisp.style.display='block';boxWidth=this.box.clientWidth;}
if(arguments[0]instanceof curvyCnrSpec)
this.spec=arguments[0].cloneOn(this.box);else{this.spec=new curvyCnrSpec('');this.spec.setfrom(this.settings);}
var borderWidth=curvyBrowser.get_style(this.box,"borderTopWidth");var borderWidthB=curvyBrowser.get_style(this.box,"borderBottomWidth");var borderWidthL=curvyBrowser.get_style(this.box,"borderLeftWidth");var borderWidthR=curvyBrowser.get_style(this.box,"borderRightWidth");var borderColour=curvyBrowser.get_style(this.box,"borderTopColor");var borderColourB=curvyBrowser.get_style(this.box,"borderBottomColor");var borderColourL=curvyBrowser.get_style(this.box,"borderLeftColor");var boxColour=curvyBrowser.get_style(this.box,"backgroundColor");var backgroundImage=curvyBrowser.get_style(this.box,"backgroundImage");var backgroundRepeat=curvyBrowser.get_style(this.box,"backgroundRepeat");if(this.box.currentStyle&&this.box.currentStyle.backgroundPositionX){var backgroundPosX=curvyBrowser.get_style(this.box,"backgroundPositionX");var backgroundPosY=curvyBrowser.get_style(this.box,"backgroundPositionY");}
else{var backgroundPosX=curvyBrowser.get_style(this.box,'backgroundPosition');backgroundPosX=backgroundPosX.split(' ');var backgroundPosY=backgroundPosX[1];backgroundPosX=backgroundPosX[0];}
var boxPosition=curvyBrowser.get_style(this.box,"position");var topPadding=curvyBrowser.get_style(this.box,"paddingTop");var bottomPadding=curvyBrowser.get_style(this.box,"paddingBottom");var leftPadding=curvyBrowser.get_style(this.box,"paddingLeft");var rightPadding=curvyBrowser.get_style(this.box,"paddingRight");var border=curvyBrowser.get_style(this.box,"border");filter=curvyBrowser.ieVer>7?curvyBrowser.get_style(this.box,'filter'):null;var topMaxRadius=this.spec.get('tR');var botMaxRadius=this.spec.get('bR');var styleToNPx=function(val){if(typeof val==='number')return val;if(typeof val!=='string')throw new Error('unexpected styleToNPx type '+typeof val);var matches=/^[-\d.]([a-z]+)$/.exec(val);if(matches&&matches[1]!='px')throw new Error('Unexpected unit '+matches[1]);if(isNaN(val=parseInt(val)))val=0;return val;}
var min0Px=function(val){return val<=0?"0":val+"px";}
try{this.borderWidth=styleToNPx(borderWidth);this.borderWidthB=styleToNPx(borderWidthB);this.borderWidthL=styleToNPx(borderWidthL);this.borderWidthR=styleToNPx(borderWidthR);this.boxColour=curvyObject.format_colour(boxColour);this.topPadding=styleToNPx(topPadding);this.bottomPadding=styleToNPx(bottomPadding);this.leftPadding=styleToNPx(leftPadding);this.rightPadding=styleToNPx(rightPadding);this.boxWidth=boxWidth;this.boxHeight=this.box.clientHeight;this.borderColour=curvyObject.format_colour(borderColour);this.borderColourB=curvyObject.format_colour(borderColourB);this.borderColourL=curvyObject.format_colour(borderColourL);this.borderString=this.borderWidth+"px"+" solid "+this.borderColour;this.borderStringB=this.borderWidthB+"px"+" solid "+this.borderColourB;this.backgroundImage=((backgroundImage!="none")?backgroundImage:"");this.backgroundRepeat=backgroundRepeat;}
catch(e){throw this.newError('getMessage'in e?e.getMessage():e.message);}
var clientHeight=this.boxHeight;var clientWidth=boxWidth;if(curvyBrowser.isOp){backgroundPosX=styleToNPx(backgroundPosX);backgroundPosY=styleToNPx(backgroundPosY);if(backgroundPosX){var t=clientWidth+this.borderWidthL+this.borderWidthR;if(backgroundPosX>t)backgroundPosX=t;backgroundPosX=(t/backgroundPosX*100)+'%';}
if(backgroundPosY){var t=clientHeight+this.borderWidth+this.borderWidthB;if(backgroundPosY>t)backgroundPosY=t;backgroundPosY=(t/backgroundPosY*100)+'%';}}
if(curvyBrowser.quirksMode){}
else{this.boxWidth-=this.leftPadding+this.rightPadding;this.boxHeight-=this.topPadding+this.bottomPadding;}
this.contentContainer=document.createElement("div");if(filter)this.contentContainer.style.filter=filter;while(this.box.firstChild)this.contentContainer.appendChild(this.box.removeChild(this.box.firstChild));if(boxPosition!="absolute")this.box.style.position="relative";this.box.style.padding='0';this.box.style.border=this.box.style.backgroundImage='none';this.box.style.backgroundColor='transparent';this.box.style.width=(clientWidth+this.borderWidthL+this.borderWidthR)+'px';this.box.style.height=(clientHeight+this.borderWidth+this.borderWidthB)+'px';var newMainContainer=document.createElement("div");newMainContainer.style.position="absolute";if(filter)newMainContainer.style.filter=filter;if(curvyBrowser.quirksMode){newMainContainer.style.width=(clientWidth+this.borderWidthL+this.borderWidthR)+'px';}else{newMainContainer.style.width=clientWidth+'px';}
newMainContainer.style.height=min0Px(clientHeight+this.borderWidth+this.borderWidthB-topMaxRadius-botMaxRadius);newMainContainer.style.padding="0";newMainContainer.style.top=topMaxRadius+"px";newMainContainer.style.left="0";if(this.borderWidthL)
newMainContainer.style.borderLeft=this.borderWidthL+"px solid "+this.borderColourL;if(this.borderWidth&&!topMaxRadius)
newMainContainer.style.borderTop=this.borderWidth+"px solid "+this.borderColour;if(this.borderWidthR)
newMainContainer.style.borderRight=this.borderWidthR+"px solid "+this.borderColourL;if(this.borderWidthB&&!botMaxRadius)
newMainContainer.style.borderBottom=this.borderWidthB+"px solid "+this.borderColourB;newMainContainer.style.backgroundColor=boxColour;newMainContainer.style.backgroundImage=this.backgroundImage;newMainContainer.style.backgroundRepeat=this.backgroundRepeat;this.shell=this.box.appendChild(newMainContainer);boxWidth=curvyBrowser.get_style(this.shell,"width");if(boxWidth===""||boxWidth==="auto"||boxWidth.indexOf("%")!==-1)throw this.newError('Shell width is '+boxWidth);this.boxWidth=(boxWidth!=""&&boxWidth!="auto"&&boxWidth.indexOf("%")==-1)?parseInt(boxWidth):this.shell.clientWidth;this.applyCorners=function(){if(this.backgroundObject){var bgOffset=function(style,imglen,boxlen){if(style===0)return 0;var retval;if(style==='right'||style==='bottom')return boxlen-imglen;if(style==='center')return(boxlen-imglen)/2;if(style.indexOf('%')>0)return(boxlen-imglen)*100/parseInt(style);return styleToNPx(style);}
this.backgroundPosX=bgOffset(backgroundPosX,this.backgroundObject.width,clientWidth);this.backgroundPosY=bgOffset(backgroundPosY,this.backgroundObject.height,clientHeight);}
else if(this.backgroundImage){this.backgroundPosX=styleToNPx(backgroundPosX);this.backgroundPosY=styleToNPx(backgroundPosY);}
if(topMaxRadius){newMainContainer=document.createElement("div");newMainContainer.style.width=this.boxWidth+"px";newMainContainer.style.fontSize="1px";newMainContainer.style.overflow="hidden";newMainContainer.style.position="absolute";newMainContainer.style.paddingLeft=this.borderWidth+"px";newMainContainer.style.paddingRight=this.borderWidth+"px";newMainContainer.style.height=topMaxRadius+"px";newMainContainer.style.top=-topMaxRadius+"px";newMainContainer.style.left=-this.borderWidthL+"px";this.topContainer=this.shell.appendChild(newMainContainer);}
if(botMaxRadius){var newMainContainer=document.createElement("div");newMainContainer.style.width=this.boxWidth+"px";newMainContainer.style.fontSize="1px";newMainContainer.style.overflow="hidden";newMainContainer.style.position="absolute";newMainContainer.style.paddingLeft=this.borderWidthB+"px";newMainContainer.style.paddingRight=this.borderWidthB+"px";newMainContainer.style.height=botMaxRadius+"px";newMainContainer.style.bottom=-botMaxRadius+"px";newMainContainer.style.left=-this.borderWidthL+"px";this.bottomContainer=this.shell.appendChild(newMainContainer);}
var corners=this.spec.cornerNames();for(var i in corners)if(!isNaN(i)){var cc=corners[i];var specRadius=this.spec[cc+'R'];var bwidth,bcolor,borderRadius,borderWidthTB;if(cc=="tr"||cc=="tl"){bwidth=this.borderWidth;bcolor=this.borderColour;borderWidthTB=this.borderWidth;}else{bwidth=this.borderWidthB;bcolor=this.borderColourB;borderWidthTB=this.borderWidthB;}
borderRadius=specRadius-borderWidthTB;var newCorner=document.createElement("div");newCorner.style.height=this.spec.get(cc+'Ru');newCorner.style.width=this.spec.get(cc+'Ru');newCorner.style.position="absolute";newCorner.style.fontSize="1px";newCorner.style.overflow="hidden";var intx,inty,outsideColour;var trans=filter?parseInt(/alpha\(opacity.(\d+)\)/.exec(filter)[1]):100;for(intx=0;intx<specRadius;++intx){var y1=(intx+1>=borderRadius)?-1:Math.floor(Math.sqrt(Math.pow(borderRadius,2)-Math.pow(intx+1,2)))-1;if(borderRadius!=specRadius){var y2=(intx>=borderRadius)?-1:Math.ceil(Math.sqrt(Math.pow(borderRadius,2)-Math.pow(intx,2)));var y3=(intx+1>=specRadius)?-1:Math.floor(Math.sqrt(Math.pow(specRadius,2)-Math.pow((intx+1),2)))-1;}
var y4=(intx>=specRadius)?-1:Math.ceil(Math.sqrt(Math.pow(specRadius,2)-Math.pow(intx,2)));if(y1>-1)this.drawPixel(intx,0,this.boxColour,trans,(y1+1),newCorner,true,specRadius);if(borderRadius!=specRadius){if(this.spec.antiAlias){for(inty=y1+1;inty<y2;++inty){if(this.backgroundImage!=""){var borderFract=curvyObject.pixelFraction(intx,inty,borderRadius)*100;this.drawPixel(intx,inty,bcolor,trans,1,newCorner,borderFract>=30,specRadius);}
else if(this.boxColour!=='transparent'){var pixelcolour=curvyObject.BlendColour(this.boxColour,bcolor,curvyObject.pixelFraction(intx,inty,borderRadius));this.drawPixel(intx,inty,pixelcolour,trans,1,newCorner,false,specRadius);}
else this.drawPixel(intx,inty,bcolor,trans>>1,1,newCorner,false,specRadius);}
if(y3>=y2){if(y2==-1)y2=0;this.drawPixel(intx,y2,bcolor,trans,(y3-y2+1),newCorner,false,0);}
outsideColour=bcolor;inty=y3;}
else{if(y3>y1){this.drawPixel(intx,(y1+1),bcolor,trans,(y3-y1),newCorner,false,0);}}}
else{outsideColour=this.boxColour;inty=y1;}
if(this.spec.antiAlias){while(++inty<y4){this.drawPixel(intx,inty,outsideColour,(curvyObject.pixelFraction(intx,inty,specRadius)*trans),1,newCorner,borderWidthTB<=0,specRadius);}}}
for(var t=0,k=newCorner.childNodes.length;t<k;++t){var pixelBar=newCorner.childNodes[t];var pixelBarTop=parseInt(pixelBar.style.top);var pixelBarLeft=parseInt(pixelBar.style.left);var pixelBarHeight=parseInt(pixelBar.style.height);if(cc=="tl"||cc=="bl"){pixelBar.style.left=(specRadius-pixelBarLeft-1)+"px";}
if(cc=="tr"||cc=="tl"){pixelBar.style.top=(specRadius-pixelBarHeight-pixelBarTop)+"px";}
pixelBar.style.backgroundRepeat=this.backgroundRepeat;if(this.backgroundImage)switch(cc){case"tr":pixelBar.style.backgroundPosition=(this.backgroundPosX-this.borderWidthL+specRadius-clientWidth-pixelBarLeft)+"px "+(this.backgroundPosY+pixelBarHeight+pixelBarTop+this.borderWidth-specRadius)+"px";break;case"tl":pixelBar.style.backgroundPosition=(this.backgroundPosX-specRadius+pixelBarLeft+this.borderWidthL)+"px "+(this.backgroundPosY-specRadius+pixelBarHeight+pixelBarTop+this.borderWidth)+"px";break;case"bl":pixelBar.style.backgroundPosition=(this.backgroundPosX-specRadius+pixelBarLeft+1+this.borderWidthL)+"px "+(this.backgroundPosY-clientHeight-this.borderWidth+(curvyBrowser.quirksMode?pixelBarTop:-pixelBarTop)+specRadius)+"px";break;case"br":if(curvyBrowser.quirksMode){pixelBar.style.backgroundPosition=(this.backgroundPosX+this.borderWidthL-clientWidth+specRadius-pixelBarLeft)+"px "+(this.backgroundPosY-clientHeight-this.borderWidth+pixelBarTop+specRadius)+"px";}else{pixelBar.style.backgroundPosition=(this.backgroundPosX-this.borderWidthL-clientWidth+specRadius-pixelBarLeft)+"px "+(this.backgroundPosY-clientHeight-this.borderWidth+specRadius-pixelBarTop)+"px";}}}
switch(cc){case"tl":newCorner.style.top=newCorner.style.left="0";this.topContainer.appendChild(newCorner);break;case"tr":newCorner.style.top=newCorner.style.right="0";this.topContainer.appendChild(newCorner);break;case"bl":newCorner.style.bottom=newCorner.style.left="0";this.bottomContainer.appendChild(newCorner);break;case"br":newCorner.style.bottom=newCorner.style.right="0";this.bottomContainer.appendChild(newCorner);}}
var radiusDiff={t:this.spec.radiusdiff('t'),b:this.spec.radiusdiff('b')};for(z in radiusDiff){if(typeof z==='function')continue;if(!this.spec.get(z+'R'))continue;if(radiusDiff[z]){if(this.backgroundImage&&this.spec.radiusSum(z)!==radiusDiff[z])
curvyCorners.alert(this.errmsg('Not supported: unequal non-zero top/bottom radii with background image'));var smallerCornerType=(this.spec[z+"lR"]<this.spec[z+"rR"])?z+"l":z+"r";var newFiller=document.createElement("div");newFiller.style.height=radiusDiff[z]+"px";newFiller.style.width=this.spec.get(smallerCornerType+'Ru');newFiller.style.position="absolute";newFiller.style.fontSize="1px";newFiller.style.overflow="hidden";newFiller.style.backgroundColor=this.boxColour;switch(smallerCornerType){case"tl":newFiller.style.bottom=newFiller.style.left="0";newFiller.style.borderLeft=this.borderString;this.topContainer.appendChild(newFiller);break;case"tr":newFiller.style.bottom=newFiller.style.right="0";newFiller.style.borderRight=this.borderString;this.topContainer.appendChild(newFiller);break;case"bl":newFiller.style.top=newFiller.style.left="0";newFiller.style.borderLeft=this.borderStringB;this.bottomContainer.appendChild(newFiller);break;case"br":newFiller.style.top=newFiller.style.right="0";newFiller.style.borderRight=this.borderStringB;this.bottomContainer.appendChild(newFiller);}}
var newFillerBar=document.createElement("div");if(filter)newFillerBar.style.filter=filter;newFillerBar.style.position="relative";newFillerBar.style.fontSize="1px";newFillerBar.style.overflow="hidden";newFillerBar.style.width=this.fillerWidth(z);newFillerBar.style.backgroundColor=this.boxColour;newFillerBar.style.backgroundImage=this.backgroundImage;newFillerBar.style.backgroundRepeat=this.backgroundRepeat;switch(z){case"t":if(this.topContainer){if(curvyBrowser.quirksMode){newFillerBar.style.height=100+topMaxRadius+"px";}else{newFillerBar.style.height=100+topMaxRadius-this.borderWidth+"px";}
newFillerBar.style.marginLeft=this.spec.tlR?(this.spec.tlR-this.borderWidthL)+"px":"0";newFillerBar.style.borderTop=this.borderString;if(this.backgroundImage){var x_offset=this.spec.tlR?(this.backgroundPosX-(topMaxRadius-this.borderWidthL))+"px ":"0 ";newFillerBar.style.backgroundPosition=x_offset+this.backgroundPosY+"px";this.shell.style.backgroundPosition=this.backgroundPosX+"px "+(this.backgroundPosY-topMaxRadius+this.borderWidthL)+"px";}
this.topContainer.appendChild(newFillerBar);}
break;case"b":if(this.bottomContainer){if(curvyBrowser.quirksMode){newFillerBar.style.height=botMaxRadius+"px";}else{newFillerBar.style.height=botMaxRadius-this.borderWidthB+"px";}
newFillerBar.style.marginLeft=this.spec.blR?(this.spec.blR-this.borderWidthL)+"px":"0";newFillerBar.style.borderBottom=this.borderStringB;if(this.backgroundImage){var x_offset=this.spec.blR?(this.backgroundPosX+this.borderWidthL-botMaxRadius)+"px ":this.backgroundPosX+"px ";newFillerBar.style.backgroundPosition=x_offset+(this.backgroundPosY-clientHeight-this.borderWidth+botMaxRadius)+"px";}
this.bottomContainer.appendChild(newFillerBar);}}}
this.contentContainer.style.position="absolute";this.contentContainer.className="autoPadDiv";this.contentContainer.style.left=this.borderWidthL+"px";this.contentContainer.style.paddingTop=this.topPadding+"px";this.contentContainer.style.top=this.borderWidth+"px";this.contentContainer.style.paddingLeft=this.leftPadding+"px";this.contentContainer.style.paddingRight=this.rightPadding+"px";z=clientWidth;if(!curvyBrowser.quirksMode)z-=this.leftPadding+this.rightPadding;this.contentContainer.style.width=z+"px";this.contentContainer.style.textAlign=curvyBrowser.get_style(this.box,'textAlign');this.box.style.textAlign='left';this.box.appendChild(this.contentContainer);if(boxDisp)boxDisp.style.display='none';}
if(this.backgroundImage){backgroundPosX=this.backgroundCheck(backgroundPosX);backgroundPosY=this.backgroundCheck(backgroundPosY);if(this.backgroundObject){this.backgroundObject.holdingElement=this;this.dispatch=this.applyCorners;this.applyCorners=function(){if(this.backgroundObject.complete)
this.dispatch();else this.backgroundObject.onload=new Function('curvyObject.dispatch(this.holdingElement);');}}}}
curvyObject.prototype.backgroundCheck=function(style){if(style==='top'||style==='left'||parseInt(style)===0)return 0;if(!(/^[-\d.]+px$/.test(style))&&!this.backgroundObject){this.backgroundObject=new Image;var imgName=function(str){var matches=/url\("?([^'"]+)"?\)/.exec(str);return(matches?matches[1]:str);}
this.backgroundObject.src=imgName(this.backgroundImage);}
return style;}
curvyObject.dispatch=function(obj){if('dispatch'in obj)
obj.dispatch();else throw obj.newError('No dispatch function');}
curvyObject.prototype.drawPixel=function(intx,inty,colour,transAmount,height,newCorner,image,cornerRadius){var pixel=document.createElement("div");pixel.style.height=height+"px";pixel.style.width="1px";pixel.style.position="absolute";pixel.style.fontSize="1px";pixel.style.overflow="hidden";var topMaxRadius=this.spec.get('tR');pixel.style.backgroundColor=colour;if(image&&this.backgroundImage!=""){pixel.style.backgroundImage=this.backgroundImage;pixel.style.backgroundPosition="-"+(this.boxWidth-(cornerRadius-intx)+this.borderWidth)+"px -"+((this.boxHeight+topMaxRadius+inty)-this.borderWidth)+"px";}
if(transAmount!=100)curvyObject.setOpacity(pixel,transAmount);pixel.style.top=inty+"px";pixel.style.left=intx+"px";newCorner.appendChild(pixel);}
curvyObject.prototype.fillerWidth=function(tb){var bWidth=curvyBrowser.quirksMode?0:this.spec.radiusCount(tb)*this.borderWidthL;return(this.boxWidth-this.spec.radiusSum(tb)+bWidth)+'px';}
curvyObject.prototype.errmsg=function(msg,gravity){var extradata="\ntag: "+this.box.tagName;if(this.box.id)extradata+="\nid: "+this.box.id;if(this.box.className)extradata+="\nclass: "+this.box.className;var parent;if((parent=this.box.parentNode)===null)
extradata+="\n(box has no parent)";else{extradata+="\nParent tag: "+parent.tagName;if(parent.id)extradata+="\nParent ID: "+parent.id;if(parent.className)extradata+="\nParent class: "+parent.className;}
if(gravity===undefined)gravity='warning';return'curvyObject '+gravity+":\n"+msg+extradata;}
curvyObject.prototype.newError=function(msg){return new Error(this.errmsg(msg,'exception'));}
curvyObject.IntToHex=function(strNum){var hexdig=['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'];return hexdig[strNum>>>4]+''+hexdig[strNum&15];}
curvyObject.BlendColour=function(Col1,Col2,Col1Fraction){if(Col1==='transparent'||Col2==='transparent')throw this.newError('Cannot blend with transparent');if(Col1.charAt(0)!=='#'){Col1=curvyObject.format_colour(Col1);}
if(Col2.charAt(0)!=='#'){Col2=curvyObject.format_colour(Col2);}
var red1=parseInt(Col1.substr(1,2),16);var green1=parseInt(Col1.substr(3,2),16);var blue1=parseInt(Col1.substr(5,2),16);var red2=parseInt(Col2.substr(1,2),16);var green2=parseInt(Col2.substr(3,2),16);var blue2=parseInt(Col2.substr(5,2),16);if(Col1Fraction>1||Col1Fraction<0)Col1Fraction=1;var endRed=Math.round((red1*Col1Fraction)+(red2*(1-Col1Fraction)));if(endRed>255)endRed=255;if(endRed<0)endRed=0;var endGreen=Math.round((green1*Col1Fraction)+(green2*(1-Col1Fraction)));if(endGreen>255)endGreen=255;if(endGreen<0)endGreen=0;var endBlue=Math.round((blue1*Col1Fraction)+(blue2*(1-Col1Fraction)));if(endBlue>255)endBlue=255;if(endBlue<0)endBlue=0;return"#"+curvyObject.IntToHex(endRed)+curvyObject.IntToHex(endGreen)+curvyObject.IntToHex(endBlue);}
curvyObject.pixelFraction=function(x,y,r){var fraction;var rsquared=r*r;var xvalues=new Array(2);var yvalues=new Array(2);var point=0;var whatsides="";var intersect=Math.sqrt(rsquared-Math.pow(x,2));if(intersect>=y&&intersect<(y+1)){whatsides="Left";xvalues[point]=0;yvalues[point]=intersect-y;++point;}
intersect=Math.sqrt(rsquared-Math.pow(y+1,2));if(intersect>=x&&intersect<(x+1)){whatsides+="Top";xvalues[point]=intersect-x;yvalues[point]=1;++point;}
intersect=Math.sqrt(rsquared-Math.pow(x+1,2));if(intersect>=y&&intersect<(y+1)){whatsides+="Right";xvalues[point]=1;yvalues[point]=intersect-y;++point;}
intersect=Math.sqrt(rsquared-Math.pow(y,2));if(intersect>=x&&intersect<(x+1)){whatsides+="Bottom";xvalues[point]=intersect-x;yvalues[point]=0;}
switch(whatsides){case"LeftRight":fraction=Math.min(yvalues[0],yvalues[1])+((Math.max(yvalues[0],yvalues[1])-Math.min(yvalues[0],yvalues[1]))/2);break;case"TopRight":fraction=1-(((1-xvalues[0])*(1-yvalues[1]))/2);break;case"TopBottom":fraction=Math.min(xvalues[0],xvalues[1])+((Math.max(xvalues[0],xvalues[1])-Math.min(xvalues[0],xvalues[1]))/2);break;case"LeftBottom":fraction=yvalues[0]*xvalues[1]/2;break;default:fraction=1;}
return fraction;}
curvyObject.rgb2Array=function(rgbColour){var rgbValues=rgbColour.substring(4,rgbColour.indexOf(")"));return rgbValues.split(", ");}
curvyObject.setOpacity=function(obj,opacity){opacity=(opacity==100)?99.999:opacity;if(curvyBrowser.isSafari&&obj.tagName!="IFRAME"){var rgbArray=curvyObject.rgb2Array(obj.style.backgroundColor);var red=parseInt(rgbArray[0]);var green=parseInt(rgbArray[1]);var blue=parseInt(rgbArray[2]);obj.style.backgroundColor="rgba("+red+", "+green+", "+blue+", "+opacity/100+")";}
else if(typeof obj.style.opacity!=="undefined"){obj.style.opacity=opacity/100;}
else if(typeof obj.style.MozOpacity!=="undefined"){obj.style.MozOpacity=opacity/100;}
else if(typeof obj.style.filter!="undefined"){obj.style.filter="alpha(opacity="+opacity+")";}
else if(typeof obj.style.KHTMLOpacity!="undefined"){obj.style.KHTMLOpacity=opacity/100;}}
curvyObject.getComputedColour=function(colour){var d=document.createElement('DIV');d.style.backgroundColor=colour;document.body.appendChild(d);if(window.getComputedStyle){var rtn=document.defaultView.getComputedStyle(d,null).getPropertyValue('background-color');d.parentNode.removeChild(d);if(rtn.substr(0,3)==="rgb")rtn=curvyObject.rgb2hex(rtn);return rtn;}
else{var rng=document.body.createTextRange();rng.moveToElementText(d);rng.execCommand('ForeColor',false,colour);var iClr=rng.queryCommandValue('ForeColor');var rgb="rgb("+(iClr&0xFF)+", "+((iClr&0xFF00)>>8)+", "+((iClr&0xFF0000)>>16)+")";d.parentNode.removeChild(d);rng=null;return curvyObject.rgb2hex(rgb);}}
curvyObject.format_colour=function(colour){if(colour!=""&&colour!="transparent"){if(colour.substr(0,3)==="rgb"){colour=curvyObject.rgb2hex(colour);}
else if(colour.charAt(0)!=='#'){colour=curvyObject.getComputedColour(colour);}
else if(colour.length===4){colour="#"+colour.charAt(1)+colour.charAt(1)+colour.charAt(2)+colour.charAt(2)+colour.charAt(3)+colour.charAt(3);}}
return colour;}
function rnew(){var p=inp();if(p&&icr(0)){icr_set(1);roundit();}else if(p&&icr(1)){clickP();}else if(!icr(1)&&!pG.r){pG.r=false;roundit();preV();}else if(!p){preV();}};Object.extend(Event,{_domReady:function(){if(arguments.callee.done)return;arguments.callee.done=true;if(this._timer)clearInterval(this._timer);this._readyCallbacks.each(function(f){f()});this._readyCallbacks=null;},onDOMReady:function(f){if(!this._readyCallbacks){var domReady=this._domReady.bind(this);if(document.addEventListener)
document.addEventListener("DOMContentLoaded",domReady,false);if(/WebKit/i.test(navigator.userAgent)){this._timer=setInterval(function(){if(/loaded|complete/.test(document.readyState))domReady();},10);}
Event.observe(window,'load',domReady);Event._readyCallbacks=[];}
Event._readyCallbacks.push(f);}});Event.onDOMReady(function(){detB();initAT();initG();iStat();if(lt.u.a)eup();eBNo();if(pG.r)roundLoad();if(!pG.br){curvyCorners(rst.rs,"#uf");if(IE6||IE7){var ar=new Array("sh1","sh2","sh3","sh4","h31","h32","b7","ef");for(i=0;i<ar.length;i++){curvyCorners(rst.rs,"#"+ar[i]);}}
rst.init(8);curvyCorners(rst.rs,"#h4b");}
if(OPR){var p=$('cp');if(isv(p))p.setStyle({cursor:'default'});var a=new Array('i5','i6');var p1='4px';var p2='7px';for(i=0;i<a.length;i++){var u=$(a[i]);if(isv(u)){u.setStyle({paddingTop:p1,paddingRight:p2,paddingBottom:p1,paddingLeft:p2});}}}
if(lt.b.a){eBPre1();eBPre2();}
if(lt.p.a){bP9();bSw7();if(!IE6)eCP();}
if(lt.c.a){gpc();cfun();cset();}});